"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, ChevronRight, CloudDownload, Code2, CreditCard, FileText, Globe2, LayoutDashboard, Mail, MessageSquare, Palette, RotateCcw, Save, Settings2, Share2, Shield, Truck, Upload, Webhook, X } from "lucide-react";
import { motion } from "framer-motion";
import type { PublicSettings, SettingsDocument } from "@/lib/settings";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

type Section = keyof SettingsDocument | "backup";
type Value = string | boolean;
type SectionValues = Record<string, Value>;
const sections: Array<{ id: Section; label: string; icon: React.ElementType }> = [
  { id: "general", label: "General", icon: Settings2 }, { id: "payment", label: "Payments", icon: CreditCard }, { id: "discord", label: "Discord", icon: Webhook }, { id: "email", label: "Email", icon: Mail }, { id: "seo", label: "SEO", icon: Globe2 }, { id: "social", label: "Social media", icon: Share2 }, { id: "analytics", label: "Analytics", icon: Code2 }, { id: "shipping", label: "Shipping", icon: Truck }, { id: "invoice", label: "Invoice", icon: FileText }, { id: "security", label: "Security", icon: Shield }, { id: "homepage", label: "Homepage CMS", icon: LayoutDashboard }, { id: "contact", label: "Contact CMS", icon: MessageSquare }, { id: "brand", label: "Brand colors", icon: Palette }, { id: "backup", label: "Backup", icon: CloudDownload }
];

function SectionTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-8"><p className="eyebrow">{eyebrow}</p><h2 className="display mt-3 text-4xl font-semibold tracking-[-.04em] text-ink">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>; }
function Field({ label, value, onChange, type = "text", placeholder, help, secret = false }: { label: string; value: Value; onChange: (value: Value) => void; type?: "text" | "email" | "url" | "number" | "password"; placeholder?: string; help?: string; secret?: boolean }) { return <div><Label>{label}</Label><Input type={type} value={String(value)} placeholder={placeholder} autoComplete={secret ? "new-password" : undefined} onChange={(event) => onChange(event.target.value)} />{help && <p className="mt-2 text-[11px] leading-5 text-muted">{help}</p>}</div>; }
function Toggle({ label, checked, onChange, description }: { label: string; checked: boolean; onChange: (value: boolean) => void; description?: string }) { return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-2xl border border-clay-200 bg-card px-4 py-3 transition hover:border-clay-300"><span><span className="block text-sm font-semibold text-ink">{label}</span>{description && <span className="mt-1 block text-xs text-muted">{description}</span>}</span><button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={cn("relative h-6 w-11 shrink-0 rounded-full p-1 transition-colors", checked ? "bg-clay-500" : "bg-clay-200")}><span className={cn("block h-4 w-4 rounded-full bg-white shadow-sm transition-transform", checked ? "translate-x-5" : "translate-x-0")} /></button></label>; }
function FieldGrid({ children }: { children: React.ReactNode }) { return <div className="grid gap-5 sm:grid-cols-2">{children}</div>; }

export function SettingsClient({ initialSettings }: { initialSettings: PublicSettings }) {
  const [settings, setSettings] = useState<PublicSettings>(initialSettings);
  const [active, setActive] = useState<Section>("general");
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [autoSave, setAutoSave] = useState(false);
  const [search, setSearch] = useState("");
  const [toast, setToast] = useState("");
  const values = useCallback((section: Section) => section === "backup" ? {} : settings[section] as SectionValues, [settings]);
  const update = useCallback((section: Section, key: string, value: Value) => { if (section === "backup") return; setSettings((current) => ({ ...current, [section]: { ...(current[section] as SectionValues), [key]: value } })); setDirty(true); }, []);
  const save = useCallback(async (silent = false) => { setSaving(true); try { const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json() as { ok?: boolean; settings?: PublicSettings; error?: string }; if (!response.ok) throw new Error(body.error ?? "Unable to save settings."); if (body.settings) setSettings(body.settings); setDirty(false); if (!silent) { setToast("Settings saved"); window.setTimeout(() => setToast(""), 2400); } } catch (error) { setToast(error instanceof Error ? error.message : "Unable to save settings."); window.setTimeout(() => setToast(""), 3000); } finally { setSaving(false); } }, [settings]);
  useEffect(() => { if (!dirty || !autoSave) return; const timer = window.setTimeout(() => void save(true), 1500); return () => window.clearTimeout(timer); }, [autoSave, dirty, save]);
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", beforeUnload); return () => window.removeEventListener("beforeunload", beforeUnload); }, [dirty]);
  const runTest = async (type: "discord" | "email" | "razorpay" | "shiprocket") => { setToast(`Testing ${type}…`); const response = await fetch("/api/admin/settings/test", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type }) }); const body = await response.json() as { message?: string; error?: string }; setToast(body.message ?? body.error ?? "Test completed"); window.setTimeout(() => setToast(""), 3000); };
  const exportSettings = () => { const blob = new Blob([JSON.stringify(settings, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "joyguru-settings.json"; link.click(); URL.revokeObjectURL(url); };
  const importSettings = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { setSettings(JSON.parse(String(reader.result)) as PublicSettings); setDirty(true); setToast("Settings imported. Review and save."); } catch { setToast("Invalid settings JSON."); } }; reader.readAsText(file); };
  const resetSettings = async () => { if (!window.confirm("Reset all settings to the Joyguru defaults? Stored credentials will be removed.")) return; setSaving(true); const response = await fetch("/api/admin/settings", { method: "DELETE" }); const body = await response.json() as { settings?: PublicSettings; error?: string }; setSaving(false); if (response.ok && body.settings) { setSettings(body.settings); setDirty(false); setToast("Settings reset to defaults."); } else setToast(body.error ?? "Unable to reset settings."); window.setTimeout(() => setToast(""), 3000); };
  const section = values(active);
  const render = (() => {
    const f = (key: string, label: string, type: "text" | "email" | "url" | "number" | "password" = "text", help?: string, secret = false) => <Field key={key} label={label} value={section[key] ?? ""} onChange={(value) => update(active, key, value)} type={type} help={help} secret={secret} />;
    const t = (key: string, label: string, description?: string) => <Toggle key={key} label={label} checked={Boolean(section[key])} onChange={(value) => update(active, key, value)} description={description} />;
    if (active === "general") return <><SectionTitle eyebrow="Workspace / 01" title="General settings" description="The identity and operating details used throughout the Joyguru Enterprise experience." /><FieldGrid>{f("companyName", "Company name")} {f("ownerName", "Owner name")} {f("websiteTitle", "Website title")} {f("supportEmail", "Support email", "email")} {f("businessEmail", "Business email", "email")} {f("phone", "Phone")} {f("whatsapp", "WhatsApp")} {f("gstNumber", "GST number")} {f("workingHours", "Working hours")}</FieldGrid><div className="mt-5"><Label>Address</Label><Textarea value={String(section.address ?? "")} onChange={(event) => update(active, "address", event.target.value)} /></div><div className="mt-8"><p className="eyebrow">Brand assets</p><p className="mt-2 text-xs text-muted">Use verified public asset URLs or paths from your media storage. Secrets are never returned to this form.</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{f("logoUrl", "Logo asset URL", "url")} {f("darkLogoUrl", "Dark logo asset URL", "url")} {f("faviconUrl", "Favicon asset URL", "url")} {f("seoImageUrl", "SEO image asset URL", "url")}</div></div></>;
    if (active === "payment") return <><SectionTitle eyebrow="Workspace / 02" title="Payment settings" description="Control available payment rails and order thresholds. Secret values are encrypted before persistence and redacted from GET responses." /><div className="grid gap-3 sm:grid-cols-2">{t("enabledRazorpay", "Enable Razorpay")} {t("enabledCod", "Enable cash on delivery")} {t("enabledBankTransfer", "Enable bank transfer")} {t("enabledUpi", "Enable UPI")} {t("testMode", "Test mode")} {t("liveMode", "Live mode")}</div><div className="mt-8"><p className="eyebrow">Gateway credentials</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{f("razorpayKeyId", "Razorpay key ID", "password", "Leave blank to keep the stored value.", true)} {f("razorpaySecret", "Razorpay secret", "password", "Encrypted at rest. Never exposed through the client API.", true)} {f("webhookSecret", "Webhook secret", "password", "Encrypted at rest.", true)} {f("currency", "Currency")}</div></div><div className="mt-8"><p className="eyebrow">Checkout rules</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{f("taxPercentage", "Tax percentage", "number")} {f("shippingCharges", "Shipping charges", "number")} {f("freeShippingLimit", "Free shipping limit", "number")} {f("minimumOrderAmount", "Minimum order amount", "number")} {f("maximumCodAmount", "Maximum COD amount", "number")}</div></div><div className="mt-8 flex flex-wrap gap-3"><Button type="button" onClick={() => void runTest("razorpay")} variant="quiet"><CreditCard size={16} />Test Razorpay</Button></div></>;
    if (active === "discord") return <><SectionTitle eyebrow="Workspace / 03" title="Discord notifications" description="Operational events are queued asynchronously, retried up to three times and never block customer requests." />{t("enabled", "Enable Discord notifications")}<div className="mt-5">{f("webhookUrl", "Discord webhook URL", "password", settings.configuredSecrets.discord ? "A webhook is already configured. Leave blank to retain it." : "Stored encrypted. Never returned to the browser.", true)}</div><div className="mt-5">{f("brandImage", "Discord brand image URL", "url")}</div><div className="mt-8"><p className="eyebrow">Event toggles</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{["newOrder", "paymentSuccess", "paymentFailed", "refund", "adminLogin", "failedLogin", "newsletter", "wholesale", "contact", "lowStock", "outOfStock", "serverStartup", "deployment", "productCreated", "productUpdated", "productDeleted"].map((key) => t(key, key.replace(/([A-Z])/g, " $1").replace(/^./, (char) => char.toUpperCase())))}</div></div><div className="mt-8 flex flex-wrap gap-3"><Button type="button" onClick={() => void runTest("discord")}><Webhook size={16} />Test webhook</Button></div></>;
    if (active === "email") return <><SectionTitle eyebrow="Workspace / 04" title="Email settings" description="Configure transactional email identity without exposing provider secrets to client components." /><div className="grid gap-3 sm:grid-cols-2">{t("enabled", "Enable emails")} {t("orderEmails", "Order emails")} {t("shippingEmails", "Shipping emails")} {t("newsletterEmails", "Newsletter emails")} {t("passwordResetEmails", "Password reset emails")} {t("welcomeEmails", "Welcome emails")}</div><div className="mt-8 rounded-3xl border border-clay-200 bg-card p-5"><p className="eyebrow">Email provider</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-between rounded-2xl border border-clay-200 px-4 py-3"><span className="text-sm font-semibold text-ink">Resend</span><input type="radio" name="email-provider" checked={String(section.provider ?? "resend") === "resend"} onChange={() => update(active, "provider", "resend")} /></label><label className="flex cursor-pointer items-center justify-between rounded-2xl border border-clay-200 px-4 py-3"><span className="text-sm font-semibold text-ink">SMTP</span><input type="radio" name="email-provider" checked={String(section.provider ?? "resend") === "smtp"} onChange={() => update(active, "provider", "smtp")} /></label></div>{String(section.provider ?? "resend") === "smtp" ? <div className="mt-6 grid gap-5 sm:grid-cols-2">{f("smtpHost", "SMTP host")} {f("smtpPort", "SMTP port", "number")} {f("smtpUsername", "SMTP username")} {f("smtpPassword", "SMTP password", "password", "Encrypted at rest. Leave blank to retain.", true)} <div><Label>Encryption</Label><select value={String(section.smtpEncryption ?? "STARTTLS")} onChange={(event) => update(active, "smtpEncryption", event.target.value)} className="h-10 w-full rounded-2xl border border-clay-200 bg-card px-3 text-sm text-ink outline-none focus:ring-2 focus:ring-clay-200"><option value="TLS">TLS</option><option value="SSL">SSL</option><option value="STARTTLS">STARTTLS</option><option value="None">None</option></select></div> {f("senderEmail", "Sender email", "email")} {f("senderName", "Sender name")} {f("replyTo", "Reply-to email", "email")}</div> : <div className="mt-6 grid gap-5 sm:grid-cols-2">{f("resendApiKey", "Resend API key", "password", "Encrypted at rest. Leave blank to retain.", true)} {f("senderEmail", "Sender email", "email")} {f("senderName", "Sender name")} {f("replyTo", "Reply-to email", "email")}</div>}</div><div className="mt-8"><Button type="button" onClick={() => void runTest("email")} variant="quiet"><Mail size={16} />Test email</Button></div></>;
    if (active === "seo") return <><SectionTitle eyebrow="Workspace / 05" title="SEO settings" description="Control search metadata and verification values from one place." /><FieldGrid>{f("siteTitle", "Site title")} {f("canonicalUrl", "Canonical URL", "url")} {f("googleVerification", "Google verification")} {f("bingVerification", "Bing verification")} {f("facebookVerification", "Facebook verification")} {f("ogImage", "Open Graph image", "url")} {f("twitterImage", "Twitter image", "url")}</FieldGrid><div className="mt-5"><Label>Meta description</Label><Textarea value={String(section.metaDescription ?? "")} onChange={(event) => update(active, "metaDescription", event.target.value)} /></div><div className="mt-5"><Label>Keywords</Label><Input value={String(section.keywords ?? "")} onChange={(event) => update(active, "keywords", event.target.value)} /></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{t("robotsEnabled", "Robots")} {t("sitemapEnabled", "Sitemap")} {t("schemaEnabled", "Structured data")}</div></>;
    if (active === "social") return <><SectionTitle eyebrow="Workspace / 06" title="Social media" description="Manage the social destinations shown across the storefront." /><FieldGrid>{["facebook", "instagram", "youtube", "twitter", "linkedin", "pinterest", "whatsapp", "telegram", "discord"].map((key) => f(key, key.replace(/^./, (char) => char.toUpperCase()), "url"))}</FieldGrid></>;
    if (active === "analytics") return <><SectionTitle eyebrow="Workspace / 07" title="Analytics" description="Keep measurement identifiers centralized and toggle tracking without editing code." /><div className="mb-5">{t("trackingEnabled", "Enable tracking", "Tracking identifiers remain inert while disabled.")}</div><FieldGrid>{["googleAnalytics", "googleTagManager", "facebookPixel", "microsoftClarity", "hotjar", "metaPixel"].map((key) => f(key, key.replace(/([A-Z])/g, " $1").replace(/^./, (char) => char.toUpperCase())))}</FieldGrid></>;
    if (active === "shipping") return <><SectionTitle eyebrow="Workspace / 08" title="Shipping settings" description="Set the visible shipping promise and cost model used by customer-facing content. Shiprocket credentials are encrypted and redacted from the browser." /><FieldGrid>{f("shippingCharge", "Shipping charge", "number")} {f("freeShipping", "Free shipping limit", "number")} {f("packagingCharge", "Packaging charge", "number")} {f("deliveryDays", "Delivery days")}</FieldGrid><div className="mt-8 rounded-3xl border border-clay-200 bg-card p-5"><p className="eyebrow">Shiprocket integration</p><p className="mt-2 text-xs text-muted">Enable Shiprocket to create and manage shipments from admin without exposing API credentials in the client.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Toggle label="Enable Shiprocket integration" checked={Boolean(section.shiprocketEnabled)} onChange={(value) => update(active, "shiprocketEnabled", value)} description="Keep credentials secured and only perform shipment creation when enabled." /><Toggle label="Auto create shipment" checked={Boolean(section.shiprocketAutoCreateShipment)} onChange={(value) => update(active, "shiprocketAutoCreateShipment", value)} description="Automatically create Shiprocket shipment for eligible orders." /><Toggle label="Auto assign courier/AWB" checked={Boolean(section.shiprocketAutoAssignAwb)} onChange={(value) => update(active, "shiprocketAutoAssignAwb", value)} description="Attempt to assign courier and AWB after shipment creation." /></div><div className="mt-8 grid gap-5 sm:grid-cols-2">{f("shiprocketEmail", "Shiprocket API email", "email", settings.configuredSecrets.shipping ? "Leave blank to retain the stored value." : "Stored encrypted. Never returned to the browser.", true)} {f("shiprocketPassword", "Shiprocket API password", "password", settings.configuredSecrets.shipping ? "Leave blank to retain the stored value." : "Stored encrypted. Never returned to the browser.", true)} {f("shiprocketPickupLocation", "Shiprocket pickup location", "text", "Enter the exact pickup location name from Shiprocket dashboard.")} </div><div className="mt-5 flex flex-wrap gap-3"><Button type="button" variant="quiet" onClick={() => void runTest("shiprocket")}><Truck size={16} />Test Shiprocket</Button></div></div><div className="mt-6 flex flex-wrap gap-3"><Button type="button" onClick={() => void save()} disabled={saving || !dirty}><Save size={16} />Save shipping settings</Button></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><Label>Courier name</Label><Input type="text" value={String(section.courierName)} onChange={(event) => update(active, "courierName", event.target.value)} /></div><div><Label>Tracking URL</Label><Input type="url" value={String(section.trackingUrl)} onChange={(event) => update(active, "trackingUrl", event.target.value)} /></div></div></>;
    if (active === "invoice") return <><SectionTitle eyebrow="Workspace / 09" title="Invoice settings" description="Shape the invoice identity and footer language used by your operations team." /><FieldGrid>{f("invoicePrefix", "Invoice prefix")} {f("companySignature", "Company signature")} {f("gst", "GST")} {f("qrCodeUrl", "QR code asset URL", "url")}</FieldGrid><div className="mt-5"><Label>Invoice footer</Label><Textarea value={String(section.invoiceFooter ?? "")} onChange={(event) => update(active, "invoiceFooter", event.target.value)} /></div><div className="mt-5"><Label>Terms</Label><Textarea value={String(section.terms ?? "")} onChange={(event) => update(active, "terms", event.target.value)} /></div><div className="mt-5"><Label>Bank details</Label><Textarea value={String(section.bankDetails ?? "")} onChange={(event) => update(active, "bankDetails", event.target.value)} /></div></>;
    if (active === "security") return <><SectionTitle eyebrow="Workspace / 10" title="Security settings" description="Control storefront access and session policy. Changes take effect in the consuming server flows once wired to the settings resolver." /><div className="grid gap-3 sm:grid-cols-2">{t("maintenanceMode", "Maintenance mode")} {t("registrationEnabled", "Allow registration")} {t("guestCheckoutEnabled", "Allow guest checkout")} {t("emailVerificationEnabled", "Require email verification")} {t("adminTwoFactorEnabled", "Require admin 2FA")}</div><div className="mt-5 grid gap-5 sm:grid-cols-2">{f("rateLimit", "Rate limit per minute", "number")} {f("sessionTimeout", "Session timeout")}</div></>;
    if (active === "homepage") return <><SectionTitle eyebrow="Workspace / 11" title="Homepage CMS" description="Edit the words, links, imagery and section visibility that shape the front of house." /><FieldGrid>{f("heroTitle", "Hero title")} {f("heroSubtitle", "Hero subtitle")} {f("heroPrimaryLabel", "Primary button label")} {f("heroPrimaryHref", "Primary button URL")} {f("heroSecondaryLabel", "Secondary button label")} {f("heroSecondaryHref", "Secondary button URL")} {f("heroBackgroundUrl", "Hero background URL", "url")} {f("heroImageUrl", "Hero image URL", "url")}</FieldGrid><div className="mt-8 grid gap-3 sm:grid-cols-2">{t("hero3dEnabled", "Hero 3D scene")} {t("collectionsEnabled", "Collections section")} {t("featuredProductsEnabled", "Featured products")} {t("testimonialsEnabled", "Testimonials")} {t("wholesaleEnabled", "Wholesale section")} {t("newsletterEnabled", "Newsletter")}</div><div className="mt-5"><Label>Footer CTA</Label><Input value={String(section.footerCta ?? "")} onChange={(event) => update(active, "footerCta", event.target.value)} /></div></>;
    if (active === "contact") return <><SectionTitle eyebrow="Workspace / 12" title="Contact CMS" description="Keep every support touchpoint and business-hour detail synchronized." /><FieldGrid>{f("googleMapsUrl", "Google Maps URL", "url")} {f("supportNumber", "Support number")} {f("whatsapp", "WhatsApp")} {f("email", "Email", "email")} {f("businessHours", "Business hours")}</FieldGrid><div className="mt-5"><Label>Office address</Label><Textarea value={String(section.officeAddress ?? "")} onChange={(event) => update(active, "officeAddress", event.target.value)} /></div></>;
    if (active === "brand") return <><SectionTitle eyebrow="Workspace / 13" title="Brand colors" description="Preview the color system used by Joyguru Enterprise. Saving persists the theme tokens for the storefront theme resolver." /><div className="grid gap-4 sm:grid-cols-2">{["primary", "secondary", "background", "card", "heading", "text", "border", "hover", "footer"].map((key) => <div key={key} className="flex items-end gap-3"><div className="relative h-12 w-12 overflow-hidden rounded-xl border border-clay-200"><input type="color" aria-label={`${key} color`} value={String(section[key] ?? "#000000")} onChange={(event) => update(active, key, event.target.value)} className="absolute -inset-2 h-16 w-16 cursor-pointer" /></div>{f(key, key.replace(/^./, (char) => char.toUpperCase()))}</div>)}</div><div className="mt-10 rounded-3xl p-8" style={{ background: String(section.background), color: String(section.heading) }}><p className="eyebrow" style={{ color: String(section.primary) }}>Live preview</p><p className="display mt-3 text-4xl font-semibold">Objects with an old soul.</p><div className="mt-6 inline-flex rounded-full px-5 py-3 text-sm font-semibold text-white" style={{ background: String(section.primary) }}>Primary action</div></div></>;
    return <><SectionTitle eyebrow="Workspace / 14" title="Backup and restore" description="Download a redacted settings snapshot or import a JSON configuration for review. Encrypted secrets are never exported." /><div className="grid gap-4 sm:grid-cols-2"><button type="button" onClick={exportSettings} className="button-quiet justify-start"><CloudDownload size={17} />Download redacted JSON</button><label className="button-quiet cursor-pointer justify-start"><Upload size={17} />Import JSON<input type="file" accept="application/json" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) importSettings(file); }} /></label></div><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><p className="font-semibold">Reset settings</p><p className="mt-1">Restore all editable configuration to the Joyguru defaults. Encrypted credentials are removed.</p><button type="button" onClick={() => void resetSettings()} className="mt-4 inline-flex items-center gap-2 rounded-full border border-amber-300 px-4 py-2 text-xs font-semibold transition hover:bg-amber-100"><RotateCcw size={14} />Reset all settings</button></div></>;
  })();
  const visibleSections = sections.filter((item) => item.label.toLowerCase().includes(search.toLowerCase()));
  return <main className="min-h-screen bg-[#f4eee8]"><div className="container-shell py-8 lg:py-12"><div className="flex flex-col justify-between gap-5 border-b border-clay-200 pb-7 md:flex-row md:items-end"><div><p className="eyebrow">Admin / Settings</p><h1 className="display mt-3 text-5xl font-semibold tracking-[-.05em] text-ink">Control room.</h1><p className="mt-3 text-sm text-muted">One place for the systems, identity and language behind Joyguru Enterprise.</p></div><div className="flex items-center gap-3"><span className="hidden text-xs text-muted sm:block">{dirty ? "Unsaved changes" : "All changes saved"}</span><label className="flex items-center gap-2 text-xs font-semibold text-muted"><input type="checkbox" checked={autoSave} onChange={(event) => setAutoSave(event.target.checked)} className="h-4 w-4 accent-clay-500" />Auto-save</label><Button type="button" onClick={() => void save()} disabled={saving || !dirty}><Save size={16} />{saving ? "Saving…" : "Save changes"}</Button></div></div><div className="mt-8 grid gap-8 lg:grid-cols-[230px_1fr]"><aside className="lg:sticky lg:top-24 lg:self-start"><div className="rounded-3xl border border-clay-200 bg-card p-2"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search settings" aria-label="Search settings" className="mb-2 h-10 w-full rounded-2xl bg-clay-100 px-3 text-xs text-ink outline-none placeholder:text-muted focus:ring-2 focus:ring-clay-200" />{visibleSections.map((item) => { const Icon = item.icon; return <button type="button" key={item.id} onClick={() => setActive(item.id)} className={cn("flex w-full items-center gap-3 rounded-2xl px-3 py-2.5 text-left text-xs font-semibold transition", active === item.id ? "bg-ink text-white" : "text-muted hover:bg-clay-100 hover:text-ink")}><Icon size={15} />{item.label}{active === item.id && <ChevronRight size={14} className="ml-auto" />}</button>; })}</div><p className="mt-4 px-3 text-[10px] leading-5 text-muted">Settings are encrypted at rest where credentials are involved. Never paste secrets into screenshots or support tickets.</p></aside><section className="min-w-0 rounded-[2rem] border border-clay-200 bg-[#fbf8f4] p-6 shadow-card sm:p-10"><motion.div key={active} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .3, ease: [0.22, 1, .36, 1] }}>{render}</motion.div></section></div></div>{toast && <motion.div initial={{ opacity: 0, y: 12, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} className="fixed bottom-6 right-6 z-50 flex max-w-sm items-center gap-3 rounded-2xl border border-clay-200 bg-ink px-4 py-3 text-sm text-white shadow-soft"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-clay-300 text-ink"><Check size={14} /></span>{toast}<button type="button" aria-label="Dismiss notification" onClick={() => setToast("")} className="ml-2 text-white/60 hover:text-white"><X size={15} /></button></motion.div>}</main>;
}
