export type ShipmentStatus = "PENDING" | "CREATED" | "AWB_ASSIGNED" | "PICKUP_SCHEDULED" | "IN_TRANSIT" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELLED" | "RETURNED";
export type ShipmentAddress = { name: string; phone: string; line1: string; city: string; state: string; pincode: string; country?: string };
<<<<<<< HEAD
export type CreateShipmentInput = { orderId: string; orderNumber: string; customerName: string; phone: string; email: string; address: ShipmentAddress; items: Array<{ name: string; sku?: string; quantity: number; price: number }>; subtotal: number; shipping: number; total: number; paymentMethod: string; weight: number; pickupLocation: string };
export type ShipmentResult = { providerShipmentId?: string; awb?: string; courier?: string; labelUrl?: string; trackingUrl?: string; status: ShipmentStatus; raw: unknown };
export interface ShippingProvider { readonly name: string; createShipment(input: CreateShipmentInput): Promise<ShipmentResult>; assignAwb(shipmentId: string, courierId?: number): Promise<ShipmentResult>; schedulePickup(shipmentId: string): Promise<ShipmentResult>; getTracking(awb: string): Promise<ShipmentResult>; cancelShipment(awb: string): Promise<ShipmentResult>; }
=======
export type CreateShipmentInput = { orderId: string; orderNumber: string; customerName: string; phone: string; email: string; address: ShipmentAddress; items: Array<{ name: string; sku?: string; quantity: number; price: number }>; subtotal: number; shipping: number; total: number; paymentMethod: string; weight: number; pickupLocation: string; dimensions?: { length?: number; breadth?: number; height?: number } };
export type ShipmentResult = { providerShipmentId?: string; shiprocketOrderId?: string; shiprocketShipmentId?: string; awb?: string; courier?: string; labelUrl?: string; trackingUrl?: string; status: ShipmentStatus; raw: unknown };
export interface ShippingProvider { readonly name: string; createShipment(input: CreateShipmentInput): Promise<ShipmentResult>; assignAwb(shipmentId: string, courierId?: number): Promise<ShipmentResult>; schedulePickup(shipmentId: string): Promise<ShipmentResult>; getTracking(awb: string): Promise<ShipmentResult>; cancelShipment(awb: string): Promise<ShipmentResult>; testConnection?(): Promise<string>; getPickupLocations?(): Promise<string[]>; }
>>>>>>> c5c08d70c3339368c786db8aec452e0478facf79
