import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const variantSchema = z.object({ name: z.string().min(1).max(120), sku: z.string().min(1).max(80), priceDelta: z.coerce.number().finite().default(0), stock: z.coerce.number().int().min(0).default(0) });
const imageSchema = z.object({ url: z.string().url().or(z.string().startsWith("/")), alt: z.string().min(1).max(180), sortOrder: z.number().int().min(0) });
const productSchema = z.object({ id: z.string().cuid().optional(), categoryId: z.string().cuid(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), name: z.string().min(2).max(180), description: z.string().min(10).max(10_000), price: z.coerce.number().positive(), compareAt: z.coerce.number().positive().nullable().optional(), wholesalePrice: z.coerce.number().positive().nullable().optional(), stock: z.coerce.number().int().min(0), lowStockAt: z.coerce.number().int().min(0).default(5), material: z.string().min(2), dimensions: z.string().min(2), weight: z.string().min(1), usage: z.string().min(2), benefits: z.array(z.string().min(1)).default([]), featured: z.boolean().default(false), active: z.boolean().default(true), images: z.array(imageSchema).default([]), variants: z.array(variantSchema).default([]) });
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
const include = { category: true, images: { orderBy: { sortOrder: "asc" as const } }, variants: { orderBy: { name: "asc" as const } } };
export async function GET(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const query = new URL(request.url).searchParams.get("q")?.trim(); const products = await prisma.product.findMany({ where: query ? { OR: [{ name: { contains: query, mode: "insensitive" } }, { slug: { contains: query, mode: "insensitive" } }] } : undefined, orderBy: { createdAt: "desc" }, take: 250, include }); return NextResponse.json({ products }); }
export async function POST(request: Request) { const user = await admin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { action?: string; id?: string; ids?: string[]; product?: unknown } | null; if (body?.action === "delete") return deleteProducts(body.ids); if (body?.action === "duplicate" && body.id) { const source = await prisma.product.findUnique({ where: { id: body.id }, include: { images: true, variants: true } }); if (!source) return NextResponse.json({ error: "Product not found." }, { status: 404 }); const product = await prisma.product.create({ data: { categoryId: source.categoryId, slug: `${source.slug}-copy-${Date.now()}`, name: `${source.name} Copy`, description: source.description, price: source.price, compareAt: source.compareAt, wholesalePrice: source.wholesalePrice, stock: 0, lowStockAt: source.lowStockAt, material: source.material, dimensions: source.dimensions, weight: source.weight, usage: source.usage, benefits: source.benefits, featured: false, active: false, images: { create: source.images.map((image) => ({ url: image.url, alt: image.alt, sortOrder: image.sortOrder })) }, variants: { create: source.variants.map((variant) => ({ name: variant.name, sku: `${variant.sku}-COPY-${Date.now()}`, priceDelta: variant.priceDelta, stock: 0 })) } }, include }); await prisma.activityLog.create({ data: { userId: user.id, action: "CREATE", entity: "Product", entityId: product.id, metadata: { duplicatedFrom: source.id } } }); return NextResponse.json({ ok: true, product }); } const parsed = productSchema.safeParse(body?.product); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid product." }, { status: 400 }); try { const product = await prisma.product.create({ data: { ...parsed.data, compareAt: parsed.data.compareAt ?? null, wholesalePrice: parsed.data.wholesalePrice ?? null, images: { create: parsed.data.images }, variants: { create: parsed.data.variants } }, include }); await prisma.activityLog.create({ data: { userId: user.id, action: "CREATE", entity: "Product", entityId: product.id, newValue: { name: product.name, slug: product.slug, price: product.price, stock: product.stock } } }); return NextResponse.json({ ok: true, product }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create product." }, { status: 409 }); } }
export async function PATCH(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = productSchema.required({ id: true }).safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid product." }, { status: 400 }); const { id, images, variants, ...data } = parsed.data; try { const product = await prisma.$transaction(async (tx) => { await tx.productImage.deleteMany({ where: { productId: id } }); await tx.productVariant.deleteMany({ where: { productId: id } }); return tx.product.update({ where: { id }, data: { ...data, compareAt: data.compareAt ?? null, wholesalePrice: data.wholesalePrice ?? null, images: { create: images }, variants: { create: variants } }, include }); }); await prisma.activityLog.create({ data: { userId: (await admin())?.id, action: "UPDATE", entity: "Product", entityId: id, newValue: data as never } }); return NextResponse.json({ ok: true, product }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update product." }, { status: 409 }); } }
async function deleteProducts(ids: string[] | undefined) { const parsed = z.array(z.string().cuid()).max(100).safeParse(ids); if (!parsed.success || !parsed.data.length) return NextResponse.json({ error: "Select products to delete." }, { status: 400 }); await prisma.product.deleteMany({ where: { id: { in: parsed.data }, orderItems: { none: {} } } }); return NextResponse.json({ ok: true }); }
export async function DELETE(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { ids?: string[] } | null; return deleteProducts(body?.ids); }
