import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { isConfiguredSuperAdmin } from "@/lib/super-admin";
import { logProtectionAttempt } from "@/lib/super-admin-protection";
async function admin(){const user=await getCurrentUser();return user&&(user.role==="ADMIN"||user.role==="STAFF")?user:null}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){if(!await admin())return NextResponse.json({error:"Forbidden"},{status:403});const user=await prisma.user.findUnique({where:{id:(await params).id},include:{staffRoleAssignments:{include:{role:true}},activityLogs:{orderBy:{createdAt:"desc"},take:100},sessions:{where:{revokedAt:null,expiresAt:{gt:new Date()}}}}});if(!user)return NextResponse.json({error:"Staff member not found"},{status:404});return NextResponse.json({user})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const actor=await admin();if(!actor)return NextResponse.json({error:"Forbidden"},{status:403});const id=(await params).id;const target=await prisma.user.findUnique({where:{id},select:{id:true,email:true,role:true,isActive:true}});if(!target)return NextResponse.json({error:"Staff member not found"},{status:404});const p=z.object({role:z.enum(["ADMIN","STAFF"]).optional(),isActive:z.boolean().optional(),roleIds:z.array(z.string().cuid()).optional()}).safeParse(await request.json().catch(()=>null));if(!p.success)return NextResponse.json({error:"Invalid staff update"},{status:400});if(isConfiguredSuperAdmin(target.email)||actor.id===id&&(p.data.role&&p.data.role!=="ADMIN"||p.data.isActive===false)){await logProtectionAttempt({actorId:actor.id,actorEmail:actor.email,targetId:id,action:"STAFF_PERMISSION_MUTATION",reason:"Protected Super Admin mutation"});return NextResponse.json({error:"Protected Super Admin account."},{status:403});}const updated=await prisma.$transaction(async tx=>{const user=await tx.user.update({where:{id},data:{...(p.data.role?{role:p.data.role}:{}),...(p.data.isActive!==undefined?{isActive:p.data.isActive}:{})}});if(p.data.roleIds){await tx.staffRoleAssignment.deleteMany({where:{userId:id}});await tx.staffRoleAssignment.createMany({data:p.data.roleIds.map(roleId=>({userId:id,roleId})),skipDuplicates:true})}await tx.activityLog.create({data:{userId:actor.id,action:"UPDATE",entity:"User",entityId:id,previousValue:target,newValue:{role:p.data.role,isActive:p.data.isActive,roleIds:p.data.roleIds}}});return user});return NextResponse.json({ok:true,user:updated})}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const actor=await admin();if(!actor)return NextResponse.json({error:"Forbidden"},{status:403});const id=(await params).id;const target=await prisma.user.findUnique({where:{id},select:{id:true,email:true,role:true,isActive:true}});if(!target)return NextResponse.json({error:"Staff member not found"},{status:404});if(isConfiguredSuperAdmin(target.email)||target.role==="ADMIN"&&await prisma.user.count({where:{role:"ADMIN",isActive:true}})<=1){await logProtectionAttempt({actorId:actor.id,actorEmail:actor.email,targetId:id,action:"STAFF_DELETE",reason:"Protected Super Admin or last Admin"});return NextResponse.json({error:"There must always be one active Super Admin."},{status:403})}await prisma.user.update({where:{id},data:{isActive:false}});await prisma.session.updateMany({where:{userId:id},data:{revokedAt:new Date()}});await prisma.activityLog.create({data:{userId:actor.id,action:"DELETE",entity:"User",entityId:id,previousValue:target}});return NextResponse.json({ok:true})}
