"use client";
import Link from "next/link";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useState } from "react";
import { Heart, Menu, Search, ShoppingBag, UserRound, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useTheme } from "next-themes";
import { navItems } from "@/lib/constants";
import { ThemeToggle } from "@/components/theme/ThemeToggle";
import { useCart } from "@/hooks/use-cart";

export function Header({ user }: { user: { name: string; email: string } | null }) {
  const [open, setOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const pathname = usePathname();
  const { resolvedTheme } = useTheme();
  const { itemCount } = useCart();
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 18); window.addEventListener("scroll", onScroll, { passive: true }); onScroll(); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <>
    <motion.header animate={{ backgroundColor: resolvedTheme === "dark" ? (scrolled ? "rgba(45,26,16,.88)" : "rgba(45,26,16,.96)") : (scrolled ? "rgba(248,242,236,.84)" : "rgba(248,242,236,.9)") }} className={`sticky top-0 z-50 border-b border-clay-200/70 backdrop-blur-xl transition-shadow duration-500 ${scrolled ? "shadow-[0_8px_35px_rgba(90,45,20,.06)]" : ""}`}>
      <div className={`container-shell flex items-center justify-between gap-6 transition-[height] duration-500 ${scrolled ? "h-[64px]" : "h-[76px]"}`}>
        <button aria-label="Open menu" data-cursor="Menu" className="rounded-full p-2 text-muted transition active:scale-90 lg:hidden" onClick={() => setOpen(true)}><Menu size={21} /></button>
        <Link href="/" data-cursor="Home" className="group flex items-center gap-3"><motion.span whileHover={{ rotate: -8, scale: 1.05 }} className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-clay-500 shadow-card"><Image src="/images/brand/joyguru-logo.png" alt="Joyguru Enterprise" width={40} height={40} className="h-full w-full object-contain" /></motion.span><span className="hidden text-[11px] font-bold uppercase tracking-[.22em] text-ink sm:block">Joyguru<br /><span className="font-normal tracking-[.16em] text-muted">Enterprise</span></span></Link>
        <nav className="hidden items-center gap-10 lg:flex">{navItems.map((item) => { const active = pathname === item.href || pathname.startsWith(`${item.href}/`); return <Link data-cursor="Open" key={item.href} href={item.href} className={`relative py-2 text-[16px] font-medium tracking-[-.012em] transition ${active ? "text-ink" : "text-muted hover:text-clay-400"}`}>{item.label}{active && <motion.span layoutId="active-nav" className="absolute -bottom-1 left-0 right-0 h-px bg-clay-400" />}</Link>; })}</nav>
        <div className="flex items-center gap-1"><Link href="/products" data-cursor="Search" aria-label="Search" className="rounded-full p-2.5 text-muted transition hover:bg-clay-100 hover:text-ink active:scale-90"><Search size={19} strokeWidth={1.7} /></Link><Link href="/wishlist" data-cursor="Wishlist" aria-label="Wishlist" className="hidden rounded-full p-2.5 text-muted transition hover:bg-clay-100 hover:text-ink active:scale-90 sm:block"><Heart size={19} strokeWidth={1.7} /></Link><Link href="/cart" data-cursor="Bag" aria-label="Cart" className="relative rounded-full p-2.5 text-muted transition hover:bg-clay-100 hover:text-ink active:scale-90"><ShoppingBag size={19} strokeWidth={1.7} />{itemCount > 0 && <motion.span initial={{ scale: 0 }} animate={{ scale: 1 }} className="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-clay-400 px-1 text-[9px] font-bold text-white">{itemCount}</motion.span>}</Link><ThemeToggle /><div className="relative"><button type="button" aria-label="Open account menu" data-cursor="Account" onClick={() => setProfileOpen((value) => !value)} className="rounded-full p-2.5 text-muted transition hover:bg-clay-100 hover:text-ink active:scale-90"><UserRound size={19} strokeWidth={1.7} /></button><AnimatePresence>{profileOpen && <motion.div initial={{ opacity: 0, y: 8, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8 }} className="absolute right-0 top-14 z-50 w-64 rounded-2xl border border-clay-200 bg-card p-2 shadow-soft"><div className="border-b border-clay-200 px-3 py-3">{user ? <><p className="text-sm font-semibold text-ink">{user.name}</p><p className="mt-1 truncate text-xs text-muted">{user.email}</p></> : <p className="text-sm font-semibold text-ink">Welcome to Joyguru</p>}</div>{user ? <><Link href="/account" className="account-menu-link">My account</Link><Link href="/account" className="account-menu-link">Orders</Link><Link href="/wishlist" className="account-menu-link">Wishlist</Link><Link href="/account/addresses" className="account-menu-link">Addresses</Link><Link href="/account?view=coupons" className="account-menu-link">Coupons</Link><form action="/api/auth/logout" method="post"><button className="account-menu-link w-full text-left text-red-700">Logout</button></form></> : <><Link href="/account/login" className="account-menu-link">Login</Link><Link href="/account/signup" className="account-menu-link">Create account</Link></>}</motion.div>}</AnimatePresence></div></div>
      </div>
    </motion.header>
    <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[60] bg-ink/20 backdrop-blur-sm lg:hidden"><motion.div initial={{ x: "-100%" }} animate={{ x: 0 }} exit={{ x: "-100%" }} transition={{ type: "spring", stiffness: 210, damping: 25 }} className="h-full w-[min(85vw,380px)] bg-[#f8f2ec] p-6 shadow-soft"><div className="flex items-center justify-between"><span className="eyebrow">Menu</span><button aria-label="Close menu" data-cursor="Close" onClick={() => setOpen(false)} className="rounded-full p-2 transition active:scale-90"><X size={20} /></button></div><nav className="mt-16 flex flex-col gap-6">{navItems.map((item, index) => <motion.div key={item.href} initial={{ opacity: 0, x: -14 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .06 }}><Link onClick={() => setOpen(false)} data-cursor="Open" href={item.href} className="display text-4xl text-ink">{item.label}</Link></motion.div>)}<Link onClick={() => setOpen(false)} href="/account" className="text-sm font-semibold text-muted">Account →</Link></nav></motion.div></motion.div>}</AnimatePresence>
  </>;
}
