import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { adjustInventory } from "@/lib/inventory";
const schema = z.object({ productId: z.string().cuid(), variantId: z.string().cuid().optional(), warehouseId: z.string().cuid().optional(), quantityChanged: z.coerce.number().int().refine((v) => v !== 0), reason: z.enum(["MANUAL_ADJUSTMENT", "DAMAGE", "RETURN", "ORDER_CANCELLED", "REFUND", "ORDER_PLACED", "PURCHASE_ENTRY", "STOCK_TRANSFER"]), notes: z.string().max(2000).optional() });
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
export async function GET() { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const [products, history, warehouses, warehouseStocks] = await Promise.all([prisma.product.findMany({ orderBy: { stock: "asc" }, take: 250, select: { id: true, name: true, slug: true, stock: true, price: true, lowStockAt: true } }), prisma.inventoryHistory.findMany({ orderBy: { createdAt: "desc" }, take: 100, include: { product: { select: { name: true, slug: true } }, warehouse: { select: { name: true } }, variant: { select: { name: true } } } }), prisma.warehouse.findMany({ where: { active: true }, orderBy: { name: "asc" }, select: { id: true, name: true } }), prisma.warehouseStock.findMany({ select: { reserved: true, incoming: true } })]); const totalStock = products.reduce((sum, product) => sum + product.stock, 0); const inventoryValue = products.reduce((sum, product) => sum + product.stock * Number(product.price), 0); const reservedStock = warehouseStocks.reduce((sum, stock) => sum + stock.reserved, 0); const incomingStock = warehouseStocks.reduce((sum, stock) => sum + stock.incoming, 0); return NextResponse.json({ products, history, warehouses, totals: { totalStock, lowStock: products.filter((product) => product.stock > 0 && product.stock <= product.lowStockAt).length, outOfStock: products.filter((product) => product.stock === 0).length, inventoryValue, reservedStock, incomingStock } }); }
export async function POST(request: Request) { const user = await admin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid adjustment." }, { status: 400 }); try { await adjustInventory({ ...parsed.data, userId: user.id }); return NextResponse.json({ ok: true }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to adjust inventory." }, { status: 409 }); } }
