import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { readingMinutes } from "@/lib/blog";
const schema = z.object({ id: z.string().cuid().optional(), authorId: z.string().cuid().optional(), title: z.string().min(2).max(180), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), excerpt: z.string().max(500).optional(), content: z.string().min(1), categoryId: z.string().cuid().nullable().optional(), tags: z.array(z.string().min(1).max(60)).max(30).default([]), relatedPostIds: z.array(z.string().cuid()).max(20).default([]), coverImage: z.string().optional(), featuredImage: z.string().optional(), metaTitle: z.string().max(180).optional(), metaDescription: z.string().max(500).optional(), status: z.enum(["DRAFT", "PUBLISHED", "SCHEDULED"]), featured: z.boolean().default(false), scheduledAt: z.coerce.date().nullable().optional() });
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
export async function GET(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const q = new URL(request.url).searchParams.get("q")?.trim(); const posts = await prisma.blogPost.findMany({ where: q ? { OR: [{ title: { contains: q, mode: "insensitive" } }, { slug: { contains: q, mode: "insensitive" } }] } : undefined, orderBy: { updatedAt: "desc" }, take: 200, include: { category: true, author: { select: { name: true } }, _count: { select: { comments: true } } } }); return NextResponse.json({ posts }); }
export async function POST(request: Request) { const user = await admin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid blog post." }, { status: 400 }); const data = { ...parsed.data, authorId: parsed.data.authorId ?? user.id, readingTime: readingMinutes(parsed.data.content), publishedAt: parsed.data.status === "PUBLISHED" ? new Date() : null, categoryId: parsed.data.categoryId ?? null, scheduledAt: parsed.data.scheduledAt ?? null }; try { const post = parsed.data.id ? await prisma.blogPost.update({ where: { id: parsed.data.id }, data, include: { category: true } }) : await prisma.blogPost.create({ data, include: { category: true } }); return NextResponse.json({ ok: true, post }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to save post." }, { status: 409 }); } }
export async function DELETE(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { id?: string } | null; if (!body?.id) return NextResponse.json({ error: "Post id is required." }, { status: 400 }); await prisma.blogPost.delete({ where: { id: body.id } }); return NextResponse.json({ ok: true }); }
