import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { safeJsonLd } from "@/lib/seo";
import { absoluteUrl } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const author=await prisma.user.findUnique({where:{authorSlug:(await params).slug},select:{name:true,authorBio:true,authorAvatarUrl:true,authorSlug:true}});return author?{title:author.name,description:author.authorBio??undefined,alternates:{canonical:absoluteUrl(`/blog/author/${author.authorSlug}`)},openGraph:{title:author.name,description:author.authorBio??undefined,images:author.authorAvatarUrl?[author.authorAvatarUrl]:undefined}}:{title:"Author not found"}}
export default async function AuthorPage({params}:{params:Promise<{slug:string}>}){const author=await prisma.user.findUnique({where:{authorSlug:(await params).slug},include:{blogPosts:{where:{status:"PUBLISHED",publishedAt:{lte:new Date()}},orderBy:{publishedAt:"desc"},include:{category:true}}}});if(!author)notFound();const schema={"@context":"https://schema.org","@type":"Person",name:author.name,description:author.authorBio??undefined,url:absoluteUrl(`/blog/author/${author.authorSlug}`),image:author.authorAvatarUrl?absoluteUrl(author.authorAvatarUrl):undefined,sameAs:Object.values((author.authorSocialLinks??{}) as Record<string,string>)};return <main className="container-shell py-16 lg:py-24"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(schema)}}/><div className="mx-auto max-w-3xl text-center">{author.authorAvatarUrl&&<div className="relative mx-auto h-28 w-28 overflow-hidden rounded-full"><Image src={author.authorAvatarUrl} alt={author.name} fill className="object-cover"/></div>}<p className="eyebrow mt-8">The people behind the work</p><h1 className="section-title mt-4">{author.name}.</h1><p className="mx-auto mt-6 max-w-xl text-base leading-7 text-muted">{author.authorBio}</p>{author.authorWebsite&&<a href={author.authorWebsite} className="mt-5 inline-block text-sm font-semibold text-clay-500">Visit website ↗</a>}</div><div className="mx-auto mt-16 grid max-w-4xl gap-6 sm:grid-cols-2">{author.blogPosts.map(post=><Link key={post.id} href={`/blog/${post.slug}` as never} className="group"><div className="relative aspect-[1.3] overflow-hidden rounded-3xl bg-clay-100">{post.featuredImage&&<Image src={post.featuredImage} alt={post.title} fill sizes="50vw" className="object-cover transition duration-700 group-hover:scale-105"/>}</div><p className="eyebrow mt-5">{post.category?.name??"Journal"}</p><h2 className="display mt-2 text-3xl font-semibold">{post.title}</h2></Link>)}</div></main>}
