import Link from "next/link";
import Image from "next/image";
import { ArrowDown, ArrowRight, Check, ChevronRight, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { getProducts } from "@/lib/products";
import { demoCategories, demoTestimonials } from "@/lib/demo-data";
import { ProductGrid } from "@/components/product/ProductCard";
import { NewsletterForm } from "@/components/home/NewsletterForm";
import { MagneticLink } from "@/components/motion/MagneticLink";
import { Reveal } from "@/components/motion/Reveal";
import { SplitHeading } from "@/components/motion/SplitHeading";
import { CraftStory } from "@/components/home/CraftStory";
import { getPublicSettings } from "@/lib/settings";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [products, settings] = await Promise.all([getProducts({ featured: true }), getPublicSettings()]);
  const allProducts = products.length ? products : await getProducts();
  const heroLines = settings.homepage.heroTitle.split("|");
  return <main>
    <section className="grain relative min-h-[calc(100svh-76px)] overflow-hidden bg-[#ead8ca]">
      <div className="absolute -right-40 top-12 h-[560px] w-[560px] rounded-full bg-[#f8eadd]/75 blur-3xl" />
      <div className="container-shell relative grid min-h-[calc(100svh-76px)] items-center gap-10 py-16 lg:grid-cols-[.9fr_1.1fr] lg:py-20">
        <Reveal className="relative z-10 max-w-xl" y={30}>
          <div className="flex items-center gap-4"><span className="eyebrow">01 — The first collection</span><span className="h-px w-14 bg-clay-300" /></div>
          <SplitHeading as="h1" className="display mt-6 text-[4.7rem] font-semibold leading-[.79] tracking-[-.055em] text-ink sm:text-[7rem] lg:text-[8.5rem]">{heroLines.map((line, index) => <span key={`${line}-${index}`} className={`block ${index === 1 ? "font-medium text-clay-400" : ""}`}>{line}</span>)}</SplitHeading>
          <p className="body-copy mt-9 max-w-sm text-base">{settings.homepage.heroSubtitle}</p>
          <div className="mt-9 flex flex-wrap items-center gap-4"><MagneticLink href={settings.homepage.heroPrimaryHref || "/products"}>{settings.homepage.heroPrimaryLabel || "Explore the collection"} <ArrowRight size={16} /></MagneticLink><a href={settings.homepage.heroSecondaryHref || "/about"} className="group inline-flex items-center gap-2 text-sm font-semibold text-ink">{settings.homepage.heroSecondaryLabel || "Our story"} <span className="transition-transform group-hover:translate-x-1">↗</span></a></div>
        </Reveal>
        <Reveal className="relative mx-auto h-[520px] w-full max-w-[620px] lg:h-[650px] lg:mr-0" delay={.12} y={10}>
          <div className="absolute inset-4 rounded-[48%] bg-[#f9eee2]/75 blur-3xl" />
          <div className="absolute inset-0 overflow-hidden rounded-[46%] bg-[radial-gradient(circle_at_48%_35%,#f2c49d_0,#d38a5f_42%,#a75432_100%)] shadow-[0_40px_100px_rgba(90,45,20,.18)]"><Image src="/images/brand/joyguru-logo.png" alt="Joyguru Enterprise" fill priority sizes="(max-width: 1024px) 90vw, 50vw" className="object-contain p-16 sm:p-24 drop-shadow-[0_24px_36px_rgba(45,26,16,.22)]" /><span className="hero-particle hero-particle-one" /><span className="hero-particle hero-particle-two" /><span className="hero-particle hero-particle-three" /><span className="hero-particle hero-particle-four" /></div>
          <div className="absolute -bottom-2 left-0 rounded-2xl border border-white/60 bg-white/55 px-5 py-4 shadow-card backdrop-blur-xl"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-muted">Handmade in Bengal</p><p className="mt-1 text-sm font-semibold text-ink">Earth · fire · everyday rituals</p></div>
          <div className="absolute right-2 top-16 hidden rounded-full border border-white/60 bg-white/35 px-4 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-muted backdrop-blur-xl sm:block">Turned by hand</div>
        </Reveal>
      </div>
      <div className="container-shell absolute bottom-6 left-0 right-0 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.2em] text-muted">Scroll to discover</span><span className="flex items-center gap-3 text-xs text-muted"><span className="hidden sm:block">Take your time</span><ArrowDown size={16} className="animate-bounce" /></span></div>
    </section>

    <section className="container-shell py-24 lg:py-36"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><Reveal><p className="eyebrow">A material with a memory</p><h2 className="section-title mt-5 max-w-xl">A little more <em className="font-normal text-clay-400">soul</em> in the everyday.</h2></Reveal><Reveal delay={.1} className="max-w-xl lg:justify-self-end"><p className="body-copy text-base">Joyguru is a study in restraint: honest materials, generous shapes and objects that become more personal with use. Made in Purba Bardhaman, for homes and spaces around the world.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-clay-500">The Joyguru story <ArrowRight size={16} /></Link></Reveal></div><Reveal delay={.08} className="mt-16"><ProductGrid products={allProducts.slice(0, 4)} /></Reveal></section>

    {settings.homepage.collectionsEnabled && <section className="border-y border-clay-200 bg-[#f2e7dd] py-24 lg:py-32"><div className="container-shell grid gap-14 md:grid-cols-[.7fr_1.3fr] md:items-end"><Reveal><p className="eyebrow">Shop by feeling</p><h2 className="section-title mt-5">Find your<br /><em className="font-normal text-clay-400">kind</em> of clay.</h2></Reveal><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{demoCategories.slice(0, 5).map((category, index) => <Reveal key={category.slug} delay={index * .06} className={index === 0 ? "sm:col-span-2" : ""}><Link href={`/categories/${category.slug}`} className={`group relative block aspect-[.85] overflow-hidden rounded-3xl bg-clay-100 ${index === 0 ? "sm:aspect-[1.75]" : ""}`}><Image src={category.image} alt={category.name} fill sizes="(max-width: 640px) 50vw, 33vw" className="object-cover transition duration-1000 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-ink/75 via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 p-5"><p className="text-lg font-semibold text-white">{category.name}</p><p className="mt-1 text-xs text-white/70">{category.description}</p><span className="mt-4 inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-[.16em] text-clay-200">Explore <ChevronRight size={13} /></span></div></Link></Reveal>)}</div></div></section>}

    <section className="container-shell py-24 lg:py-36"><div className="grid gap-14 lg:grid-cols-[1fr_1fr] lg:items-center"><Reveal className="relative aspect-[.9] overflow-hidden rounded-[3rem] bg-clay-200" y={10}><Image src="/images/photography/pottery-white.jpg" alt="Handmade planter with green stem" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover transition duration-1000 hover:scale-105" /><span className="absolute bottom-5 left-5 rounded-full bg-white/55 px-4 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-muted backdrop-blur-xl">The studio, Purba Bardhaman</span></Reveal><Reveal delay={.1} className="max-w-lg lg:pl-10"><p className="eyebrow">The Joyguru way</p><h2 className="section-title mt-5">Made slowly.<br /><em className="font-normal text-clay-400">Kept forever.</em></h2><p className="body-copy mt-7 text-base">We work with local makers where every piece is thrown, trimmed, fired and finished by hand. Small variations are not imperfections — they are the signature of the person who made it.</p><div className="mt-9 grid gap-5 sm:grid-cols-2"><div className="flex gap-3"><Sparkles className="mt-1 shrink-0 text-clay-400" size={18} /><div><p className="text-sm font-semibold text-ink">Made by hand</p><p className="mt-1 text-xs leading-5 text-muted">No two pieces ever tell the same story.</p></div></div><div className="flex gap-3"><ShieldCheck className="mt-1 shrink-0 text-clay-400" size={18} /><div><p className="text-sm font-semibold text-ink">Made to last</p><p className="mt-1 text-xs leading-5 text-muted">Thoughtful materials, fired with care.</p></div></div></div><Link href="/about" className="button-quiet mt-10">Meet the makers <ArrowRight size={16} /></Link></Reveal></div></section>

    <CraftStory />

    {settings.homepage.wholesaleEnabled && <section className="relative overflow-hidden py-24 lg:py-32"><Image src="/images/photography/pottery-heritage.jpg" alt="" fill sizes="100vw" className="pointer-events-none object-cover opacity-[.08]" /><div className="container-shell relative"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><Reveal><p className="eyebrow">A considered partnership</p><h2 className="section-title mt-5">Bring a little Bengal<br /><em className="font-normal text-clay-400">to your shelves.</em></h2><Link href="/wholesale" className="button-primary mt-9">Trade enquiries <ArrowRight size={16} /></Link></Reveal><div className="grid gap-4 sm:grid-cols-2">{demoTestimonials.map((testimonial, index) => <Reveal key={testimonial.name} delay={index * .1} className="surface flex flex-col justify-between p-7"><div className="relative mb-7 h-28 overflow-hidden rounded-2xl"><Image src={index === 0 ? "/images/photography/pottery-white.jpg" : "/images/photography/pottery-earth.jpg"} alt="" fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover" /></div><p className="display text-3xl leading-[1.05] text-ink">“{testimonial.quote}”</p><div className="mt-12 border-t border-clay-200 pt-4"><p className="text-sm font-semibold text-ink">{testimonial.name}</p><p className="mt-1 text-xs text-muted">{testimonial.role}</p></div></Reveal>)}</div></div></div></section>}

    <section className="container-shell pb-24 lg:pb-32"><div className="grid gap-4 sm:grid-cols-3"><div className="surface relative overflow-hidden p-6"><Image src="/images/photography/pottery-wheel.jpg" alt="" fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover opacity-10" /><div className="relative z-10"><Truck className="text-clay-400" size={20} /><p className="mt-14 text-sm font-semibold text-ink">Careful delivery</p><p className="mt-2 text-xs leading-5 text-muted">Packed by hand, delivered across India.</p></div></div><div className="surface relative overflow-hidden p-6"><Image src="/images/photography/pottery-white.jpg" alt="" fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover opacity-10" /><div className="relative z-10"><Check className="text-clay-400" size={20} /><p className="mt-14 text-sm font-semibold text-ink">Honest materials</p><p className="mt-2 text-xs leading-5 text-muted">Clay, water, fire — nothing unnecessary.</p></div></div><div className="surface relative overflow-hidden p-6"><Image src="/images/photography/pottery-market.jpg" alt="" fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover opacity-10" /><div className="relative z-10"><Sparkles className="text-clay-400" size={20} /><p className="mt-14 text-sm font-semibold text-ink">Made for gifting</p><p className="mt-2 text-xs leading-5 text-muted">Beautiful pieces with gift-ready options.</p></div></div></div></section>

    {settings.homepage.newsletterEnabled && <section className="container-shell pb-10"><div className="relative overflow-hidden rounded-[2.5rem] bg-[#ead8ca] p-8 sm:p-12 lg:p-16"><Image src="/images/photography/pottery-white.jpg" alt="" fill sizes="100vw" className="pointer-events-none object-cover opacity-10 mix-blend-multiply" /><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full border border-white/50" /><div className="relative grid gap-6 md:grid-cols-[1fr_1fr] md:items-end"><Reveal><p className="eyebrow">A slower kind of update</p><h2 className="section-title mt-5">Notes from the<br /><em className="font-normal text-clay-400">workshop.</em></h2></Reveal><Reveal delay={.1}><p className="body-copy max-w-md">New collections, studio stories and the occasional reason to put the kettle on. No noise, just good things.</p><NewsletterForm /></Reveal></div></div></section>}
  </main>;
}
