import { NextResponse } from "next/server";
import { DeleteObjectsCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getR2Config, mediaKind, safeMediaKey } from "@/lib/r2";
const fileSchema = z.object({ name: z.string().min(1).max(180), type: z.string().min(1).max(120), size: z.number().int().positive().max(50 * 1024 * 1024), folder: z.string().trim().max(80).default("root") });
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
export async function GET(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const params = new URL(request.url).searchParams; const search = params.get("q")?.trim(); const folder = params.get("folder") ?? undefined; const assets = await prisma.mediaAsset.findMany({ where: { ...(folder ? { folder } : {}), ...(search ? { name: { contains: search, mode: "insensitive" } } : {}) }, orderBy: { createdAt: "desc" }, take: 100 }); return NextResponse.json({ assets }); }
export async function POST(request: Request) { const user = await admin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { action?: "presign" | "finalize"; file?: unknown; key?: string; name?: string; type?: string; size?: number; folder?: string; alt?: string } | null; const config = getR2Config(); if (!config) return NextResponse.json({ error: "R2 storage is not configured." }, { status: 503 }); if (body?.action === "presign") { const parsed = fileSchema.safeParse(body.file); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid file." }, { status: 400 }); const key = `${parsed.data.folder === "root" ? "media" : `media/${safeMediaKey(parsed.data.folder)}`}/${crypto.randomUUID()}-${safeMediaKey(parsed.data.name)}`; const command = new PutObjectCommand({ Bucket: config.bucket, Key: key, ContentType: parsed.data.type, ContentLength: parsed.data.size }); const uploadUrl = await getSignedUrl(config.client, command, { expiresIn: 900 }); return NextResponse.json({ uploadUrl, key, publicUrl: `${config.publicUrl}/${key}`, kind: mediaKind(parsed.data.type) }); }
  if (body?.action === "finalize") { if (!body.key || !body.name || !body.type || !body.size) return NextResponse.json({ error: "Incomplete asset metadata." }, { status: 400 }); const folder = body.folder?.trim() || "root"; const asset = await prisma.mediaAsset.create({ data: { key: body.key, url: `${config.publicUrl}/${body.key}`, name: body.name, folder, mimeType: body.type, kind: mediaKind(body.type), size: body.size, alt: body.alt?.trim() || body.name, createdById: user.id } }); return NextResponse.json({ ok: true, asset }); }
  return NextResponse.json({ error: "Unknown media action." }, { status: 400 }); }
export async function DELETE(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { ids?: string[] } | null; const ids = z.array(z.string().cuid()).max(100).safeParse(body?.ids); if (!ids.success || !ids.data.length) return NextResponse.json({ error: "Select at least one asset." }, { status: 400 }); const config = getR2Config(); if (!config) return NextResponse.json({ error: "R2 storage is not configured." }, { status: 503 }); const assets = await prisma.mediaAsset.findMany({ where: { id: { in: ids.data } }, select: { key: true } }); if (assets.length) await config.client.send(new DeleteObjectsCommand({ Bucket: config.bucket, Delete: { Objects: assets.map((asset) => ({ Key: asset.key })) } })); await prisma.mediaAsset.deleteMany({ where: { id: { in: ids.data } } }); return NextResponse.json({ ok: true }); }
