"use client";
import Script from "next/script";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useCart } from "@/hooks/use-cart";
import { formatINR } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
export function CheckoutForm() { const router = useRouter(); const { items, subtotal, clear } = useCart(); const [paymentMethod, setPaymentMethod] = useState<"COD" | "RAZORPAY">("COD"); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const shipping = subtotal >= 1999 ? 0 : 99; async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget)); const payload = { ...values, paymentMethod, items: items.map((item) => ({ productId: item.id, slug: item.slug, quantity: item.quantity })) }; const endpoint = paymentMethod === "COD" ? "/api/orders" : "/api/razorpay/orders"; const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { ok?: boolean; error?: string; key?: string; amount?: number; currency?: string; razorpayOrderId?: string; orderNumber?: string }; if (!response.ok) { setPending(false); setError(data.error ?? "Unable to start checkout."); return; } if (paymentMethod === "COD") { clear(); router.push(`/checkout/success?order=${data.orderNumber ?? ""}`); return; } if (!data.key || !data.razorpayOrderId || !data.amount || !data.currency) { setPending(false); setError("Online payment could not be started."); return; } if (!window.Razorpay) { setPending(false); setError("Payment window is still loading. Please try again."); return; } const checkout = new window.Razorpay({ key: data.key, amount: data.amount, currency: data.currency, name: "Joyguru Enterprise", description: "Handmade clayware", order_id: data.razorpayOrderId, prefill: { name: String(values.name), email: String(values.email), contact: String(values.phone) }, theme: { color: "#5A2D14" }, handler: async (payment) => { const verify = await fetch("/api/razorpay/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payment) }); const verifyData = await verify.json() as { ok?: boolean; error?: string; orderNumber?: string }; setPending(false); if (!verify.ok) return setError(verifyData.error ?? "Payment verification failed."); clear(); router.push(`/checkout/success?order=${verifyData.orderNumber ?? data.orderNumber ?? ""}`); }, modal: { ondismiss: () => setPending(false) } }); checkout.open(); }
  return <><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" /><form onSubmit={submit} className="space-y-8"><section><h2 className="text-sm font-bold uppercase tracking-[.16em] text-ink">Contact</h2><div className="mt-5"><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required /></div></section><section><h2 className="text-sm font-bold uppercase tracking-[.16em] text-ink">Delivery details</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label htmlFor="name">Full name</Label><Input id="name" name="name" required /></div><div className="sm:col-span-2"><Label htmlFor="phone">Phone</Label><Input id="phone" name="phone" type="tel" inputMode="numeric" required /></div><div className="sm:col-span-2"><Label htmlFor="address">Address</Label><Input id="address" name="address" required minLength={10} /></div><div><Label htmlFor="city">City</Label><Input id="city" name="city" required /></div><div><Label htmlFor="state">State</Label><Input id="state" name="state" required defaultValue="West Bengal" /></div><div><Label htmlFor="pincode">PIN code</Label><Input id="pincode" name="pincode" inputMode="numeric" required /></div></div></section><section><h2 className="text-sm font-bold uppercase tracking-[.16em] text-ink">Payment</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className={`cursor-pointer rounded-2xl border p-4 ${paymentMethod === "COD" ? "border-clay-400 bg-clay-100" : "border-clay-200 bg-card"}`}><input type="radio" name="payment-choice" checked={paymentMethod === "COD"} onChange={() => setPaymentMethod("COD")} className="sr-only" /><span className="text-sm font-semibold text-ink">Cash on delivery</span><span className="mt-1 block text-xs text-muted">Pay when your parcel arrives.</span></label><label className={`cursor-pointer rounded-2xl border p-4 ${paymentMethod === "RAZORPAY" ? "border-clay-400 bg-clay-100" : "border-clay-200 bg-card"}`}><input type="radio" name="payment-choice" checked={paymentMethod === "RAZORPAY"} onChange={() => setPaymentMethod("RAZORPAY")} className="sr-only" /><span className="text-sm font-semibold text-ink">Pay online</span><span className="mt-1 block text-xs text-muted">Secure payment via Razorpay.</span></label></div></section>{error && <p className="text-sm text-red-700">{error}</p>}<Button type="submit" disabled={pending || !items.length} className="w-full">{pending ? "Preparing your order…" : `${paymentMethod === "COD" ? "Place order" : "Continue to payment"} · ${formatINR(subtotal + shipping)}`}</Button><p className="text-center text-xs leading-5 text-muted">By placing your order, you agree to our terms and shipping policy.</p></form></> }
