export type CatalogProduct = {
  id: string; slug: string; name: string; category: string; categorySlug: string; description: string; price: number; compareAt: number | null; wholesalePrice: number | null; stock: number; material: string; dimensions: string; weight: string; usage: string; benefits: string[]; image: string; gallery: string[]; featured: boolean; rating: number; reviewCount: number;
};

export const catalog: CatalogProduct[] = [
  { id: "clay-001", slug: "terracotta-water-matka", name: "Terracotta Water Matka", category: "Earthenware", categorySlug: "earthenware", description: "A naturally cooling water vessel turned by hand and finished with a quiet, burnished warmth.", price: 1890, compareAt: 2290, wholesalePrice: 1260, stock: 18, material: "Natural terracotta clay", dimensions: "26 × 26 × 34 cm", weight: "3.2 kg", usage: "Water storage & serving", benefits: ["Naturally cools water", "Plastic-free living", "Each piece is unique"], image: "/images/photography/pottery-earth.jpg", gallery: ["/images/photography/pottery-earth.jpg", "/images/photography/pottery-wheel.jpg"], featured: true, rating: 4.9, reviewCount: 42 },
  { id: "clay-002", slug: "saj-bowl-set-of-four", name: "Saj Bowl Set of Four", category: "Tableware", categorySlug: "tableware", description: "Four tactile everyday bowls with a generous rim and a softly smoked, food-safe finish.", price: 1490, compareAt: null, wholesalePrice: 980, stock: 36, material: "High-fired stoneware clay", dimensions: "15 cm diameter each", weight: "1.6 kg set", usage: "Serving & dining", benefits: ["Food safe", "Dishwasher friendly", "Hand-finished rim"], image: "/images/photography/pottery-wheel.jpg", gallery: ["/images/photography/pottery-wheel.jpg", "/images/photography/pottery-earth.jpg"], featured: true, rating: 4.8, reviewCount: 29 },
  { id: "clay-003", slug: "riverline-planter", name: "Riverline Planter", category: "Planters", categorySlug: "planters", description: "A sculptural planter inspired by the sinuous banks of the Damodar, with a discreet drainage hole.", price: 2390, compareAt: 2790, wholesalePrice: 1590, stock: 12, material: "Porous terracotta clay", dimensions: "22 × 22 × 20 cm", weight: "2.1 kg", usage: "Indoor & balcony plants", benefits: ["Breathable clay", "Drainage ready", "Warm neutral palette"], image: "/images/photography/pottery-white.jpg", gallery: ["/images/photography/pottery-white.jpg", "/images/photography/ceramics-close.jpg"], featured: true, rating: 5, reviewCount: 18 },
  { id: "clay-004", slug: "monsoon-tea-set", name: "Monsoon Tea Set", category: "Tableware", categorySlug: "tableware", description: "A two-cup tea ritual set: balanced, thumb-worn and made to make a slow morning feel special.", price: 1690, compareAt: null, wholesalePrice: 1120, stock: 24, material: "Glazed red clay", dimensions: "Teapot 18 cm; cups 8 cm", weight: "1.4 kg set", usage: "Tea & coffee service", benefits: ["Lead-free glaze", "Heat retaining", "Gift-ready packaging"], image: "/images/photography/pottery-heritage.jpg", gallery: ["/images/photography/pottery-heritage.jpg", "/images/photography/pottery-wheel.jpg"], featured: true, rating: 4.9, reviewCount: 35 },
  { id: "clay-005", slug: "dusk-bud-vase", name: "Dusk Bud Vase", category: "Vases", categorySlug: "vases", description: "A small-necked vase for one stem, made to bring a little ceremony to a bedside or desk.", price: 790, compareAt: null, wholesalePrice: 490, stock: 46, material: "Hand-thrown terracotta", dimensions: "9 × 9 × 16 cm", weight: "480 g", usage: "Single stems & styling", benefits: ["Hand-thrown", "Small-space friendly", "Natural patina"], image: "/images/photography/ceramics-close.jpg", gallery: ["/images/photography/ceramics-close.jpg", "/images/photography/pottery-earth.jpg"], featured: false, rating: 4.7, reviewCount: 12 },
  { id: "clay-006", slug: "grain-keeper", name: "Grain Keeper", category: "Earthenware", categorySlug: "earthenware", description: "A lidded storage jar that keeps grains, tea or coffee close and the kitchen visually calm.", price: 1290, compareAt: null, wholesalePrice: 850, stock: 21, material: "Natural clay with cork lid", dimensions: "16 × 16 × 23 cm", weight: "1.5 kg", usage: "Dry storage", benefits: ["Breathable storage", "Cork lid", "Hand-burnished"], image: "/images/photography/pottery-wheel.jpg", gallery: ["/images/photography/pottery-wheel.jpg", "/images/photography/pottery-earth.jpg"], featured: false, rating: 4.8, reviewCount: 16 },
  { id: "clay-007", slug: "sunrise-dinner-plate", name: "Sunrise Dinner Plate", category: "Tableware", categorySlug: "tableware", description: "A wide, softly undulating plate for generous meals and a table that feels considered, not formal.", price: 890, compareAt: null, wholesalePrice: 590, stock: 58, material: "Stoneware clay", dimensions: "27 cm diameter", weight: "720 g", usage: "Dining & serving", benefits: ["Food safe glaze", "Stackable", "Oven safe"], image: "/images/photography/pottery-earth.jpg", gallery: ["/images/photography/pottery-earth.jpg", "/images/photography/pottery-wheel.jpg"], featured: false, rating: 4.6, reviewCount: 9 },
  { id: "clay-008", slug: "courtyard-diya-trio", name: "Courtyard Diya Trio", category: "Decor", categorySlug: "decor", description: "Three hand-pressed diyas with a wide flame well, made for evenings that begin at home.", price: 590, compareAt: 690, wholesalePrice: 360, stock: 72, material: "Unglazed terracotta", dimensions: "9 cm diameter each", weight: "540 g set", usage: "Oil lamps & festive decor", benefits: ["Hand-pressed", "Reusable", "Festive gifting"], image: "/images/photography/pottery-heritage.jpg", gallery: ["/images/photography/pottery-heritage.jpg", "/images/photography/ceramics-close.jpg"], featured: false, rating: 4.9, reviewCount: 26 }
  ,{ id: "clay-009", slug: "ash-grey-tumbler", name: "Ash Grey Tumbler", category: "Tableware", categorySlug: "tableware", description: "A weighty everyday tumbler with a mineral glaze and a shape that settles naturally in the hand.", price: 620, compareAt: null, wholesalePrice: 390, stock: 34, material: "High-fired stoneware clay", dimensions: "8 × 8 × 10 cm", weight: "340 g", usage: "Water, tea & coffee", benefits: ["Food safe", "Stackable", "Hand-glazed"], image: "/images/photography/pottery-wheel.jpg", gallery: ["/images/photography/pottery-wheel.jpg"], featured: false, rating: 4.7, reviewCount: 11 },
  { id: "clay-010", slug: "red-earth-serving-platter", name: "Red Earth Serving Platter", category: "Tableware", categorySlug: "tableware", description: "An expansive platter for shared meals, fruit and the generous centre of a table.", price: 2190, compareAt: null, wholesalePrice: 1440, stock: 15, material: "Red stoneware clay", dimensions: "38 × 25 × 4 cm", weight: "1.8 kg", usage: "Serving", benefits: ["Food safe glaze", "Wide rim", "Hand-finished"], image: "/images/photography/pottery-earth.jpg", gallery: ["/images/photography/pottery-earth.jpg"], featured: false, rating: 4.9, reviewCount: 14 },
  { id: "clay-011", slug: "quiet-lassi-glass-set", name: "Quiet Lassi Glass Set", category: "Tableware", categorySlug: "tableware", description: "A set of two clay glasses that make even a weekday drink feel rooted and refreshing.", price: 940, compareAt: null, wholesalePrice: 610, stock: 28, material: "Natural terracotta", dimensions: "8 × 8 × 12 cm each", weight: "620 g set", usage: "Drinks & serving", benefits: ["Naturally cools", "Food safe", "Set of two"], image: "/images/photography/pottery-heritage.jpg", gallery: ["/images/photography/pottery-heritage.jpg"], featured: false, rating: 4.8, reviewCount: 8 },
  { id: "clay-012", slug: "fieldstone-casserole", name: "Fieldstone Casserole", category: "Earthenware", categorySlug: "earthenware", description: "A deep, covered casserole for slow cooking, serving and keeping comfort close.", price: 2490, compareAt: 2890, wholesalePrice: 1650, stock: 10, material: "High-fired clay", dimensions: "26 × 20 × 12 cm", weight: "2.4 kg", usage: "Cooking & serving", benefits: ["Oven safe", "Heat retaining", "Covered design"], image: "/images/photography/pottery-wheel.jpg", gallery: ["/images/photography/pottery-wheel.jpg"], featured: false, rating: 4.9, reviewCount: 21 },
  { id: "clay-013", slug: "bengal-bell-planter", name: "Bengal Bell Planter", category: "Planters", categorySlug: "planters", description: "A softly flared planter with a quiet bell silhouette for herbs and leafy companions.", price: 1190, compareAt: null, wholesalePrice: 750, stock: 31, material: "Porous terracotta clay", dimensions: "18 × 18 × 17 cm", weight: "1.3 kg", usage: "Indoor plants", benefits: ["Drainage ready", "Breathable clay", "Warm patina"], image: "/images/photography/pottery-white.jpg", gallery: ["/images/photography/pottery-white.jpg"], featured: false, rating: 4.6, reviewCount: 7 },
  { id: "clay-014", slug: "terrace-herb-trio", name: "Terrace Herb Trio", category: "Planters", categorySlug: "planters", description: "Three compact pots made for mint, basil and the small pleasure of growing something.", price: 1390, compareAt: 1590, wholesalePrice: 890, stock: 22, material: "Hand-thrown terracotta", dimensions: "12 × 12 × 13 cm each", weight: "1.6 kg set", usage: "Herbs & small plants", benefits: ["Set of three", "Drainage ready", "Outdoor friendly"], image: "/images/photography/pottery-white.jpg", gallery: ["/images/photography/pottery-white.jpg"], featured: false, rating: 4.8, reviewCount: 13 },
  { id: "clay-015", slug: "cinder-tall-vase", name: "Cinder Tall Vase", category: "Vases", categorySlug: "vases", description: "A tall, slender silhouette with enough presence for branches and enough quiet for a shelf.", price: 1890, compareAt: null, wholesalePrice: 1190, stock: 17, material: "Smoked terracotta", dimensions: "14 × 14 × 32 cm", weight: "1.4 kg", usage: "Branches & florals", benefits: ["Stable base", "Hand-smoked finish", "One-of-a-kind texture"], image: "/images/photography/ceramics-close.jpg", gallery: ["/images/photography/ceramics-close.jpg"], featured: false, rating: 4.7, reviewCount: 10 },
  { id: "clay-016", slug: "sindur-red-bud-vase", name: "Sindur Red Bud Vase", category: "Vases", categorySlug: "vases", description: "A warm red bud vase with a narrow opening for a single thoughtful stem.", price: 690, compareAt: null, wholesalePrice: 430, stock: 40, material: "Red clay", dimensions: "8 × 8 × 15 cm", weight: "420 g", usage: "Single stems", benefits: ["Hand-thrown", "Small-space friendly", "Natural pigment"], image: "/images/photography/ceramics-close.jpg", gallery: ["/images/photography/ceramics-close.jpg"], featured: false, rating: 4.8, reviewCount: 16 },
  { id: "clay-017", slug: "quiet-incense-holder", name: "Quiet Incense Holder", category: "Decor", categorySlug: "decor", description: "A small, grounded holder for incense, made to bring a little pause into the room.", price: 490, compareAt: null, wholesalePrice: 280, stock: 66, material: "Unglazed clay", dimensions: "10 × 7 × 3 cm", weight: "180 g", usage: "Incense & rituals", benefits: ["Easy to clean", "Hand-pressed", "Giftable"], image: "/images/photography/pottery-heritage.jpg", gallery: ["/images/photography/pottery-heritage.jpg"], featured: false, rating: 4.9, reviewCount: 19 },
  { id: "clay-018", slug: "evening-lamp-pair", name: "Evening Lamp Pair", category: "Decor", categorySlug: "decor", description: "Two small lamps with generous flame wells for a gentle glow at dinner or dusk.", price: 890, compareAt: 990, wholesalePrice: 550, stock: 38, material: "Unglazed terracotta", dimensions: "12 × 8 × 5 cm each", weight: "440 g pair", usage: "Oil lamps & decor", benefits: ["Pair of two", "Reusable", "Hand-pressed"], image: "/images/photography/pottery-heritage.jpg", gallery: ["/images/photography/pottery-heritage.jpg"], featured: false, rating: 4.8, reviewCount: 22 },
  { id: "clay-019", slug: "river-mouth-pitcher", name: "River Mouth Pitcher", category: "Earthenware", categorySlug: "earthenware", description: "A generous pitcher with an easy pour and a silhouette inspired by water worn stone.", price: 1590, compareAt: null, wholesalePrice: 1020, stock: 20, material: "Natural terracotta clay", dimensions: "18 × 14 × 25 cm", weight: "1.7 kg", usage: "Water & table service", benefits: ["Naturally cools", "Easy-pour spout", "Hand-burnished"], image: "/images/photography/pottery-earth.jpg", gallery: ["/images/photography/pottery-earth.jpg"], featured: false, rating: 4.7, reviewCount: 15 },
  { id: "clay-020", slug: "grain-pot-small", name: "Grain Pot Small", category: "Earthenware", categorySlug: "earthenware", description: "A small lidded pot for spices, tea leaves or anything worth keeping close at hand.", price: 790, compareAt: null, wholesalePrice: 500, stock: 44, material: "Natural clay with cork lid", dimensions: "12 × 12 × 16 cm", weight: "680 g", usage: "Dry storage", benefits: ["Cork lid", "Breathable storage", "Hand-burnished"], image: "/images/photography/pottery-wheel.jpg", gallery: ["/images/photography/pottery-wheel.jpg"], featured: false, rating: 4.8, reviewCount: 9 },
  { id: "clay-021", slug: "dawn-mug-pair", name: "Dawn Mug Pair", category: "Tableware", categorySlug: "tableware", description: "Two generous mugs with a thumb-friendly handle and a soft sunrise glaze.", price: 1090, compareAt: null, wholesalePrice: 690, stock: 29, material: "Stoneware clay", dimensions: "10 × 8 × 10 cm each", weight: "720 g pair", usage: "Tea & coffee", benefits: ["Lead-free glaze", "Comfortable handle", "Set of two"], image: "/images/photography/pottery-heritage.jpg", gallery: ["/images/photography/pottery-heritage.jpg"], featured: false, rating: 4.9, reviewCount: 18 },
  { id: "clay-022", slug: "moon-serving-bowl", name: "Moon Serving Bowl", category: "Tableware", categorySlug: "tableware", description: "A deep serving bowl for curries, fruit and the centre of a generous table.", price: 1690, compareAt: null, wholesalePrice: 1090, stock: 19, material: "High-fired stoneware", dimensions: "25 × 25 × 10 cm", weight: "1.4 kg", usage: "Serving & dining", benefits: ["Food safe", "Generous capacity", "Hand-finished rim"], image: "/images/photography/pottery-wheel.jpg", gallery: ["/images/photography/pottery-wheel.jpg"], featured: false, rating: 4.8, reviewCount: 12 },
  { id: "clay-023", slug: "little-leaf-planter", name: "Little Leaf Planter", category: "Planters", categorySlug: "planters", description: "A petite planter for a windowsill, shelf or the first green thing in a new home.", price: 590, compareAt: null, wholesalePrice: 350, stock: 51, material: "Porous terracotta clay", dimensions: "11 × 11 × 11 cm", weight: "430 g", usage: "Small plants", benefits: ["Drainage ready", "Small-space friendly", "Natural patina"], image: "/images/photography/pottery-white.jpg", gallery: ["/images/photography/pottery-white.jpg"], featured: false, rating: 4.7, reviewCount: 8 },
  { id: "clay-024", slug: "earth-note-vase-set", name: "Earth Note Vase Set", category: "Vases", categorySlug: "vases", description: "Three small vases designed to sit together or travel around the home with the seasons.", price: 1290, compareAt: 1490, wholesalePrice: 820, stock: 26, material: "Hand-thrown terracotta", dimensions: "7–13 cm height", weight: "760 g set", usage: "Stems & styling", benefits: ["Set of three", "Hand-thrown", "Gift-ready packaging"], image: "/images/photography/ceramics-close.jpg", gallery: ["/images/photography/ceramics-close.jpg"], featured: false, rating: 4.9, reviewCount: 17 }

];

export const categories = [
  { name: "Earthenware", slug: "earthenware", description: "Vessels that let life breathe.", image: "/images/photography/pottery-earth.jpg", count: 8 },
  { name: "Tableware", slug: "tableware", description: "The everyday, made meaningful.", image: "/images/photography/pottery-wheel.jpg", count: 7 },
  { name: "Planters", slug: "planters", description: "A softer home for green things.", image: "/images/photography/pottery-white.jpg", count: 5 },
  { name: "Vases", slug: "vases", description: "Quiet forms for wild stems.", image: "/images/photography/ceramics-close.jpg", count: 4 },
  { name: "Decor", slug: "decor", description: "Small rituals, lasting warmth.", image: "/images/photography/pottery-heritage.jpg", count: 6 }
];
