import { absoluteUrl } from "@/lib/utils";
import { createEmbed, discordColors, maskEmail, maskIp, maskPhone, sendEmbed, sanitizeDiscordText, type DiscordField } from "@/lib/discord";

function fields(entries: Array<[string, unknown, boolean?]>): DiscordField[] { return entries.map(([name, value, inline]) => ({ name, value: sanitizeDiscordText(value), inline: inline ?? true })); }
function money(value: number) { return `₹${value.toLocaleString("en-IN")}`; }
function itemList(items: Array<{ name: string; quantity: number; price?: number }>) { return items.length ? items.map((item) => `${item.name} × ${item.quantity}${item.price !== undefined ? ` · ${money(item.price * item.quantity)}` : ""}`).join("\n") : "—"; }

export type OrderDiscordInput = { orderId: string; customerName: string; phone: string; email: string; shippingAddress: string; paymentMethod: string; paymentStatus: string; total: number; shipping: number; coupon?: string; discount: number; items: Array<{ name: string; quantity: number; price?: number }>; orderUrl?: string };
export function notifyNewOrder(input: OrderDiscordInput) { sendEmbed(createEmbed({ title: "🛍️ New order received", url: input.orderUrl, color: discordColors.success, fields: fields([["Order ID", input.orderId], ["Customer", input.customerName], ["Phone", maskPhone(input.phone)], ["Email", maskEmail(input.email)], ["Shipping address", input.shippingAddress, false], ["Payment method", input.paymentMethod], ["Payment status", input.paymentStatus], ["Order total", money(input.total)], ["Shipping", input.shipping === 0 ? "Free" : money(input.shipping)], ["Coupon", input.coupon || "None"], ["Discount", money(input.discount)], ["Products", itemList(input.items), false], ["Admin dashboard", absoluteUrl(`/admin?order=${encodeURIComponent(input.orderId)}`), false], ["Order page", input.orderUrl || absoluteUrl(`/track-order?order=${encodeURIComponent(input.orderId)}`), false]]), thumbnail: input.items[0] ? absoluteUrl(`/images/photography/pottery-earth.jpg`) : undefined })); }
export function notifyPaymentSuccess(input: { orderId: string; paymentId: string; amount: number; customer: string; method: string }) { sendEmbed(createEmbed({ title: "✅ Payment successful", color: discordColors.info, fields: fields([["Order ID", input.orderId], ["Razorpay payment ID", input.paymentId], ["Amount", money(input.amount)], ["Customer", input.customer], ["Payment method", input.method], ["Payment time", new Date().toISOString()]]) })); }
export function notifyPaymentFailed(input: { orderId?: string; customer: string; reason: string; gatewayError?: string; amount?: number }) { sendEmbed(createEmbed({ title: "❌ Payment failed", color: discordColors.error, fields: fields([["Customer", input.customer], ["Order", input.orderId || "Unavailable"], ["Reason", input.reason], ["Gateway error", input.gatewayError || "Unavailable"], ["Amount", input.amount !== undefined ? money(input.amount) : "Unavailable"]]) })); }
export function notifyRefundProcessed(input: { refundId: string; amount: number; reason: string; customer: string; orderId: string }) { sendEmbed(createEmbed({ title: "💗 Refund processed", color: discordColors.pink, fields: fields([["Refund ID", input.refundId], ["Amount", money(input.amount)], ["Reason", input.reason], ["Customer", input.customer], ["Order", input.orderId]]) })); }
export function notifyNewUser(input: { name: string; email: string; role?: string }) { sendEmbed(createEmbed({ title: "👋 New user registered", color: discordColors.purple, fields: fields([["Name", input.name], ["Email", maskEmail(input.email)], ["Role", input.role || "CUSTOMER"], ["Registration time", new Date().toISOString()]]) })); }
export function notifyContact(input: { name: string; phone?: string; email: string; message: string; page?: string }) { sendEmbed(createEmbed({ title: "✉️ New contact form message", color: discordColors.orange, fields: fields([["Name", input.name], ["Phone", input.phone ? maskPhone(input.phone) : "Not provided"], ["Email", maskEmail(input.email)], ["Message", input.message, false], ["Page submitted", input.page || "/contact"], ["Time", new Date().toISOString()]]) })); }
export function notifyWholesale(input: { businessName: string; customerName: string; phone?: string; email: string; products: string; quantity: string; message: string }) { sendEmbed(createEmbed({ title: "🤝 New wholesale enquiry", color: discordColors.gold, fields: fields([["Business", input.businessName], ["Customer", input.customerName], ["Phone", input.phone ? maskPhone(input.phone) : "Not provided"], ["Email", maskEmail(input.email)], ["Requested products", input.products, false], ["Expected quantity", input.quantity], ["Message", input.message, false]]) })); }
export function notifyNewsletter(email: string) { sendEmbed(createEmbed({ title: "📮 New newsletter subscriber", color: discordColors.grey, fields: fields([["Email", maskEmail(email)], ["Subscription time", new Date().toISOString()]]) })); }
export function notifyLowStock(input: { product: string; stock: number; productId: string; slug: string }) { sendEmbed(createEmbed({ title: "⚠️ Low stock alert", color: discordColors.warning, fields: fields([["Product", input.product], ["Current stock", input.stock], ["Product ID", input.productId], ["Product link", absoluteUrl(`/products/${input.slug}`), false]]) })); }
export function notifyOutOfStock(input: { product: string; sku: string; category: string; lastQuantity: number }) { sendEmbed(createEmbed({ title: "⛔ Product out of stock", color: discordColors.darkRed, fields: fields([["Product", input.product], ["SKU", input.sku], ["Category", input.category], ["Last quantity", input.lastQuantity]]) })); }
export function notifyAdminLogin(input: { email: string; ip?: string; browser?: string; operatingSystem?: string; country?: string; success?: boolean; reason?: string }) { sendEmbed(createEmbed({ title: input.success === false ? "🚨 Failed admin login" : "🔐 Admin login", color: input.success === false ? discordColors.error : discordColors.darkGrey, fields: fields([["Admin email", maskEmail(input.email)], ["IP address", maskIp(input.ip)], ["Browser", input.browser || "Unavailable"], ["Operating system", input.operatingSystem || "Unavailable"], ["Country", input.country || "Unavailable"], ["Reason", input.reason || "Authenticated"], ["Login time", new Date().toISOString()]]) })); }
export function notifyServerStarted(input: { environment: string; version: string; build: string; nodeVersion: string }) { sendEmbed(createEmbed({ title: "🚀 Server started", color: discordColors.success, fields: fields([["Environment", input.environment], ["Version", input.version], ["Build", input.build], ["Node version", input.nodeVersion], ["Time", new Date().toISOString()]]) })); }
export function notifyDeployment(input: { environment: string; branch: string; commit: string; version: string; buildTime: string; url: string }) { sendEmbed(createEmbed({ title: "🚢 New deployment", color: discordColors.blurple, fields: fields([["Environment", input.environment], ["Branch", input.branch], ["Commit", input.commit], ["Version", input.version], ["Build time", input.buildTime], ["Deployment URL", input.url, false]]) })); }
export function notifySystemError(input: { message: string; stack?: string; url?: string; user?: string }) { sendEmbed(createEmbed({ title: "💥 System error", color: discordColors.darkRed, fields: fields([["Error message", input.message], ["Stack trace", input.stack || "Unavailable", false], ["URL", input.url || "Unavailable", false], ["User", input.user || "Anonymous"], ["Time", new Date().toISOString()]]) })); }
export function notifyProductCreated(input: { name: string; price: number; category: string; sku: string }) { sendEmbed(createEmbed({ title: "🆕 Product created", color: discordColors.success, fields: fields([["Product", input.name], ["Price", money(input.price)], ["Category", input.category], ["SKU", input.sku]]) })); }
export function notifyProductUpdated(input: { product: string; changedFields: string; editor: string }) { sendEmbed(createEmbed({ title: "✏️ Product updated", color: discordColors.info, fields: fields([["Product", input.product], ["Changed fields", input.changedFields, false], ["Editor", input.editor], ["Time", new Date().toISOString()]]) })); }
export function notifyProductDeleted(input: { product: string; sku: string; deletedBy: string }) { sendEmbed(createEmbed({ title: "🗑️ Product deleted", color: discordColors.error, fields: fields([["Product", input.product], ["SKU", input.sku], ["Deleted by", input.deletedBy], ["Time", new Date().toISOString()]]) })); }
export function notifyOrderCancelled(input: { orderId: string; customer: string; reason: string; refundStatus: string }) { sendEmbed(createEmbed({ title: "↩️ Order cancelled", color: discordColors.orange, fields: fields([["Order ID", input.orderId], ["Customer", input.customer], ["Reason", input.reason], ["Refund status", input.refundStatus]]) })); }

export function notifySuperAdminCreated(email: string) { sendEmbed(createEmbed({ title: "🛡️ Super Admin created", color: discordColors.success, fields: fields([["Account", maskEmail(email)], ["Time", new Date().toISOString()]]) })); }
export function notifySuperAdminRepaired(email: string, changes: string[]) { sendEmbed(createEmbed({ title: "🔧 Super Admin repaired", color: discordColors.warning, fields: fields([["Account", maskEmail(email)], ["Repaired fields", changes.join(", ")], ["Time", new Date().toISOString()]]) })); }
export function notifySuperAdminProtectionAttempt(input: { actorEmail: string; action: string; reason: string; ip?: string }) { sendEmbed(createEmbed({ title: "🚨 Protected Super Admin action blocked", color: discordColors.darkRed, fields: fields([["Actor", maskEmail(input.actorEmail)], ["Action", input.action], ["Reason", input.reason], ["IP", maskIp(input.ip)], ["Time", new Date().toISOString()]]) })); }
