import { prisma } from "@/lib/prisma";
import { safeQuery } from "@/lib/safe-db";
import { decryptIntegrationSecret, encryptIntegrationSecret, maskSecret } from "@/lib/integration-secrets";
import { site } from "@/lib/constants";
import { z } from "zod";

const providerSchema = z.object({ enabled: z.boolean(), mode: z.enum(["test", "live"]), credentials: z.record(z.string(), z.string()), version: z.string().default("1.0.0"), status: z.enum(["NOT_CONFIGURED", "HEALTHY", "DEGRADED", "ERROR"]).default("NOT_CONFIGURED"), lastUpdated: z.string().nullable(), lastVerified: z.string().nullable(), lastFailure: z.string().nullable().default(null), lastError: z.string().nullable(), responseTimeMs: z.number().nullable().default(null), updatedBy: z.string().nullable().default(null) });
export const integrationsSchema = z.object({ payments: z.record(z.string(), providerSchema), storage: providerSchema, delivery: z.record(z.string(), providerSchema), authentication: z.record(z.string(), providerSchema), email: z.record(z.string(), providerSchema) });
export type Integrations = z.infer<typeof integrationsSchema>;
const providers = ["razorpay", "stripe", "cashfree", "phonepe", "payu", "paypal", "manualBankTransfer"];
const deliveries = ["shiprocket", "delhivery", "shipmozo", "nimbuspost", "pickrr", "shipway", "clickpost", "easyship", "manualShipping"];
const authProviders = ["email", "google", "github", "facebook", "otp"];
const emailProviders = ["resend", "smtp", "sendgrid", "amazonSes"];
type IntegrationProvider = { enabled: boolean; mode: "test" | "live"; credentials: Record<string, string>; version: string; status: "NOT_CONFIGURED" | "HEALTHY" | "DEGRADED" | "ERROR"; lastUpdated: string | null; lastVerified: string | null; lastFailure: string | null; lastError: string | null; responseTimeMs: number | null; updatedBy: string | null };
function provider(): IntegrationProvider { return { enabled: false, mode: "test", credentials: {}, version: "1.0.0", status: "NOT_CONFIGURED", lastUpdated: null, lastVerified: null, lastFailure: null, lastError: null, responseTimeMs: null, updatedBy: null }; }
export const defaultIntegrations: Integrations = { payments: Object.fromEntries(providers.map((name) => [name, provider()])), storage: provider(), delivery: Object.fromEntries(deliveries.map((name) => [name, provider()])), authentication: Object.fromEntries(authProviders.map((name) => [name, provider()])), email: Object.fromEntries(emailProviders.map((name) => [name, provider()])) };
const secretNames = ["secret", "secretKey", "webhookSecret", "accessKeyId", "secretAccessKey", "password", "apiKey", "clientSecret", "token"];
function shouldEncrypt(name: string) { return secretNames.some((secret) => name.toLowerCase().includes(secret.toLowerCase())); }
function merge(a: Integrations, b: Partial<Integrations>): Integrations { return { ...a, ...b, payments: { ...a.payments, ...(b.payments ?? {}) }, storage: { ...a.storage, ...(b.storage ?? {}) }, delivery: { ...a.delivery, ...(b.delivery ?? {}) }, authentication: { ...a.authentication, ...(b.authentication ?? {}) }, email: { ...a.email, ...(b.email ?? {}) } } as Integrations; }
export async function getStoredIntegrations(): Promise<Integrations> { const record = await safeQuery(() => prisma.siteSetting.findUnique({ where: { key: "integrations" } }), null); if (!record) return structuredClone(defaultIntegrations); const parsed = integrationsSchema.safeParse(record.value); return parsed.success ? merge(structuredClone(defaultIntegrations), parsed.data) : structuredClone(defaultIntegrations); }
export async function getPrivateIntegrations() { const stored = await getStoredIntegrations(); const configs = [...Object.values(stored.payments), ...Object.values(stored.delivery), ...Object.values(stored.authentication), ...Object.values(stored.email), stored.storage]; for (const config of configs) { for (const [name, raw] of Object.entries(config.credentials)) { config.credentials[name] = await decryptIntegrationSecret(String(raw)); } } if (!stored.payments.razorpay.credentials.keyId) stored.payments.razorpay.credentials.keyId = process.env.RAZORPAY_KEY_ID ?? ""; if (!stored.payments.razorpay.credentials.secret) stored.payments.razorpay.credentials.secret = process.env.RAZORPAY_KEY_SECRET ?? ""; if (!stored.storage.credentials.accessKeyId) stored.storage.credentials.accessKeyId = process.env.R2_ACCESS_KEY_ID ?? ""; if (!stored.storage.credentials.secretAccessKey) stored.storage.credentials.secretAccessKey = process.env.R2_SECRET_ACCESS_KEY ?? ""; if (!stored.storage.credentials.accountId) stored.storage.credentials.accountId = process.env.R2_ACCOUNT_ID ?? ""; if (!stored.storage.credentials.bucket) stored.storage.credentials.bucket = process.env.R2_BUCKET ?? ""; if (!stored.storage.credentials.publicUrl) stored.storage.credentials.publicUrl = process.env.R2_PUBLIC_URL ?? ""; return stored; }
export async function getPublicIntegrations() { const stored = await getStoredIntegrations(); const output = structuredClone(stored); const configs = [...Object.values(output.payments), ...Object.values(output.delivery), ...Object.values(output.authentication), ...Object.values(output.email), output.storage]; for (const config of configs) { const masked: Record<string, string> = {}; for (const [name, raw] of Object.entries(config.credentials)) masked[name] = shouldEncrypt(name) ? "" : String(raw); config.credentials = masked; } return output; }
export async function saveIntegrations(input: Integrations) { const current = await getStoredIntegrations(); const next = structuredClone(input); const groups: Array<[Record<string, ReturnType<typeof provider>>, Record<string, ReturnType<typeof provider>>]> = [[next.payments, current.payments], [next.delivery, current.delivery], [next.authentication, current.authentication], [next.email, current.email]]; for (const [nextGroup, currentGroup] of groups) for (const providerName of Object.keys(nextGroup)) { const config = nextGroup[providerName]; const existing = currentGroup[providerName]; for (const [name, raw] of Object.entries(config.credentials)) { const value = String(raw); config.credentials[name] = value ? (shouldEncrypt(name) ? await encryptIntegrationSecret(value) : value) : existing?.credentials[name] ?? ""; } config.lastUpdated = new Date().toISOString(); } for (const [name, raw] of Object.entries(next.storage.credentials)) { const value = String(raw); next.storage.credentials[name] = value ? (shouldEncrypt(name) ? await encryptIntegrationSecret(value) : value) : current.storage.credentials[name] ?? ""; } next.storage.lastUpdated = new Date().toISOString(); await prisma.siteSetting.upsert({ where: { key: "integrations" }, update: { value: next as never }, create: { key: "integrations", value: next as never } }); return getPublicIntegrations(); }
export { providers, deliveries, authProviders, emailProviders };
