import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { isConfiguredSuperAdmin } from "@/lib/super-admin";
import { logProtectionAttempt } from "@/lib/super-admin-protection";
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const customer = await prisma.user.findUnique({ where: { id: (await params).id }, include: { addresses: true, orders: { orderBy: { createdAt: "desc" }, include: { items: true } }, wishlist: { include: { product: true } }, reviews: { include: { product: true }, orderBy: { createdAt: "desc" } }, customerNotes: { orderBy: { createdAt: "desc" } }, activityLogs: { orderBy: { createdAt: "desc" }, take: 50 } } }); if (!customer) return NextResponse.json({ error: "Customer not found." }, { status: 404 }); return NextResponse.json({ customer }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const adminUser = await admin(); if (!adminUser) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const id = (await params).id; const target = await prisma.user.findUnique({ where: { id }, select: { email: true, role: true } }); if (target && (target.role === "ADMIN" || isConfiguredSuperAdmin(target.email))) { await logProtectionAttempt({ actorId: adminUser.id, actorEmail: adminUser.email, targetId: id, action: "CUSTOMER_MUTATION", reason: "Administrative accounts cannot be modified through customer routes." }); return NextResponse.json({ error: "Protected administrative account." }, { status: 403 }); } const body = await request.json().catch(() => null) as { tags?: string[]; blacklisted?: boolean; note?: string } | null; const parsed = z.object({ tags: z.array(z.string().min(1).max(60)).max(30).optional(), blacklisted: z.boolean().optional(), note: z.string().max(5000).optional() }).safeParse(body); if (!parsed.success) return NextResponse.json({ error: "Invalid customer update." }, { status: 400 }); const result = await prisma.$transaction(async (tx) => { if (parsed.data.tags || parsed.data.blacklisted !== undefined) await tx.user.update({ where: { id }, data: { ...(parsed.data.tags ? { tags: parsed.data.tags } : {}), ...(parsed.data.blacklisted !== undefined ? { blacklisted: parsed.data.blacklisted } : {}) } }); if (parsed.data.note?.trim()) await tx.customerNote.create({ data: { userId: id, authorId: adminUser.id, body: parsed.data.note.trim() } }); await tx.activityLog.create({ data: { userId: adminUser.id, action: "UPDATE", entity: "Customer", entityId: id, metadata: { tags: parsed.data.tags, blacklisted: parsed.data.blacklisted, noteAdded: Boolean(parsed.data.note) } } }); return tx.user.findUnique({ where: { id }, include: { customerNotes: { orderBy: { createdAt: "desc" } } } }); }); return NextResponse.json({ ok: true, customer: result }); }
