import { NextResponse } from "next/server";
import Razorpay from "razorpay";
import { HeadBucketCommand, S3Client } from "@aws-sdk/client-s3";
import { Resend } from "resend";
import { getCurrentUser } from "@/lib/auth";
import { getPrivateIntegrations, saveIntegrations } from "@/lib/integrations";
import { prisma } from "@/lib/prisma";
import { notifyDiscord } from "@/lib/notifications";

type Group = "payments" | "storage" | "delivery" | "authentication" | "email";
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
async function record(userId: string, userEmail: string, group: Group, provider: string, ok: boolean, error: string | null, started: number) { const settings = await getPrivateIntegrations(); const config = group === "storage" ? settings.storage : (settings[group] as Record<string, { status: string; lastVerified: string | null; lastFailure: string | null; lastError: string | null; responseTimeMs: number | null; updatedBy: string | null }>)[provider]; if (!config) return; config.status = ok ? "HEALTHY" : "ERROR"; config.responseTimeMs = Date.now() - started; config.updatedBy = userEmail; if (ok) { config.lastVerified = new Date().toISOString(); config.lastError = null; } else { config.lastFailure = new Date().toISOString(); config.lastError = error; } await saveIntegrations(settings); await prisma.activityLog.create({ data: { userId, action: ok ? "UPDATE" : "LOGIN", entity: "Integration", entityId: `${group}:${provider}`, metadata: { provider, group, success: ok, error, responseTimeMs: config.responseTimeMs } } }); notifyDiscord(ok ? "Integration connected" : "Integration test failed", { Provider: provider, Group: group, Status: ok ? "Healthy" : "Error", Error: error ?? "None" }); }
export async function POST(request: Request) { const user = await admin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { group?: Group; provider?: string } | null; const group = body?.group; const provider = body?.provider; if (!group || !provider) return NextResponse.json({ error: "Provider and group are required." }, { status: 400 }); const started = Date.now(); try { const settings = await getPrivateIntegrations(); if (group === "payments" && provider === "razorpay") { const c = settings.payments.razorpay.credentials; if (!c.keyId || !c.secret) throw new Error("Razorpay credentials are not configured."); await new Razorpay({ key_id: c.keyId, key_secret: c.secret }).orders.all({ count: 1 }); await record(user.id, user.email, group, provider, true, null, started); return NextResponse.json({ ok: true, message: "Razorpay connection verified." }); } if (group === "storage") { const c = settings.storage.credentials; if (!c.accountId || !c.accessKeyId || !c.secretAccessKey || !c.bucket) throw new Error("R2 credentials are not configured."); const client = new S3Client({ region: "auto", endpoint: `https://${c.accountId}.r2.cloudflarestorage.com`, credentials: { accessKeyId: c.accessKeyId, secretAccessKey: c.secretAccessKey } }); await client.send(new HeadBucketCommand({ Bucket: c.bucket })); await record(user.id, user.email, group, "storage", true, null, started); return NextResponse.json({ ok: true, message: "Cloudflare R2 connection verified." }); } if (group === "email" && provider === "resend") { const c = settings.email.resend.credentials; if (!c.apiKey) throw new Error("Resend API key is not configured."); const result = await new Resend(c.apiKey).domains.list(); if (result.error) throw new Error(result.error.message); await record(user.id, user.email, group, provider, true, null, started); return NextResponse.json({ ok: true, message: "Resend connection verified." }); } throw new Error("Configured but adapter not installed for this provider."); } catch (error) { const message = error instanceof Error ? error.message : "Connection test failed."; await record(user.id, user.email, group, provider, false, message, started).catch(() => undefined); return NextResponse.json({ error: message }, { status: 503 }); } }
