import type { Metadata } from "next";
import Link from "next/link";
import { getProducts } from "@/lib/products";
import { categories } from "@/lib/catalog";
import { ProductGrid } from "@/components/product/ProductCard";
import { ProductSearch } from "@/components/product/ProductSearch";

export const metadata: Metadata = { title: "Shop handmade clayware", description: "Explore Joyguru Enterprise’s collection of handmade clayware from Bengal." };
export const dynamic = "force-dynamic";
export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ category?: string; q?: string }> }) { const params = await searchParams; const products = await getProducts({ category: params.category, query: params.q }); return <main className="container-shell py-16 lg:py-24"><div className="max-w-2xl"><p className="eyebrow">The collection</p><h1 className="section-title mt-4">Objects with<br /><em className="font-normal text-clay-400">an old soul.</em></h1><p className="body-copy mt-6 max-w-lg">Clayware for daily rituals — made in small batches by hands that know the earth.</p></div><div className="mt-14 flex flex-col justify-between gap-4 border-y border-clay-200 py-4 sm:flex-row sm:items-center"><div className="flex gap-2 overflow-x-auto pb-1"><Link href="/products" className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${!params.category ? "bg-ink text-white" : "text-muted hover:bg-clay-100"}`}>All pieces</Link>{categories.map((category) => <Link key={category.slug} href={`/products?category=${category.slug}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${params.category === category.slug ? "bg-ink text-white" : "text-muted hover:bg-clay-100"}`}>{category.name}</Link>)}</div><ProductSearch initialQuery={params.q} /></div><div className="mt-12">{products.length ? <ProductGrid products={products} /> : <div className="surface flex min-h-60 flex-col items-center justify-center text-center"><p className="eyebrow">No pieces found</p><p className="mt-3 text-sm text-muted">Try a different search or explore every piece.</p><Link href="/products" className="button-primary mt-6">View all pieces</Link></div>}</div></main>; }
