"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
export default function SuppliersPage() { const [suppliers, setSuppliers] = useState<{ id: string; name: string; company: string; email: string; phone: string }[]>([]); const [form, setForm] = useState({ name: "", company: "", gst: "", phone: "", email: "", address: "", notes: "" }); const load = async () => { const response = await fetch("/api/admin/suppliers", { cache: "no-store" }); if (response.ok) setSuppliers((await response.json() as { suppliers: typeof suppliers }).suppliers); };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []); const save = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch("/api/admin/suppliers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { setForm({ name: "", company: "", gst: "", phone: "", email: "", address: "", notes: "" }); await load(); } }; return <main className="container-shell py-12 lg:py-20"><a href="/admin/inventory" className="text-xs font-semibold text-muted">← Inventory</a><h1 className="section-title mt-8">Suppliers.</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px]"><section className="surface divide-y divide-clay-200">{suppliers.map((supplier) => <div key={supplier.id} className="flex justify-between gap-4 p-6"><div><p className="font-semibold">{supplier.name}</p><p className="mt-1 text-xs text-muted">{supplier.company} · {supplier.email}</p></div><p className="text-sm text-muted">{supplier.phone}</p></div>)}{!suppliers.length && <p className="p-10 text-sm text-muted">No suppliers yet.</p>}</section><form onSubmit={save} className="surface space-y-4 p-6"><p className="eyebrow">New supplier</p>{[["name","Name"],["company","Company"],["gst","GST"],["phone","Phone"],["email","Email"],["address","Address"],["notes","Notes"]].map(([key,label]) => <div key={key}><Label>{label}</Label><Input type={key === "email" ? "email" : "text"} value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required={!['gst','notes'].includes(key)} /></div>)}<Button type="submit">Add supplier</Button></form></div></main>; }
