import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { slugify } from "@/lib/utils";
const schema = z.object({ id: z.string().cuid().optional(), name: z.string().min(2).max(120), email: z.string().email(), authorSlug: z.string().min(2).regex(/^[a-z0-9-]+$/), authorBio: z.string().max(2000).optional(), authorAvatarUrl: z.string().url().or(z.string().startsWith("/")).optional(), authorWebsite: z.string().url().or(z.literal("")).optional(), authorSocialLinks: z.record(z.string(), z.string()).optional(), featuredAuthor: z.boolean().optional() });
async function admin() { const user = await getCurrentUser(); return user && (user.role === "ADMIN" || user.role === "STAFF") ? user : null; }
const select = { id: true, name: true, email: true, authorSlug: true, authorBio: true, authorAvatarUrl: true, authorWebsite: true, authorSocialLinks: true, featuredAuthor: true, blogPosts: { select: { status: true, viewCount: true } } } as const;
export async function GET(request: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const q = new URL(request.url).searchParams.get("q")?.trim(); const users = await prisma.user.findMany({ where: { authorSlug: { not: null }, ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }] } : {}) }, orderBy: { name: "asc" }, take: 250, select }); return NextResponse.json({ authors: users.map((user) => ({ ...user, publishedPostCount: user.blogPosts.filter((post) => post.status === "PUBLISHED").length, draftPostCount: user.blogPosts.filter((post) => post.status !== "PUBLISHED").length, totalViews: user.blogPosts.reduce((sum, post) => sum + post.viewCount, 0) })) }); }
export async function POST(request: Request) { const actor = await admin(); if (!actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid author." }, { status: 400 }); try { const { id, ...data } = parsed.data; const author = id ? await prisma.user.update({ where: { id }, data: { ...data, authorSlug: data.authorSlug || slugify(data.name) }, select }) : await prisma.user.create({ data: { name: data.name, email: data.email, role: "CUSTOMER", authorSlug: data.authorSlug || slugify(data.name), authorBio: data.authorBio, authorAvatarUrl: data.authorAvatarUrl, authorWebsite: data.authorWebsite, authorSocialLinks: data.authorSocialLinks, featuredAuthor: data.featuredAuthor ?? false }, select }); return NextResponse.json({ ok: true, author }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to save author." }, { status: 409 }); } }
