import { NextResponse } from "next/server";
import Razorpay from "razorpay";
import { Resend } from "resend";
import { getCurrentUser } from "@/lib/auth";
import { createEmbed, discordColors, sendEmbedNow } from "@/lib/discord";
import { getPrivateSettings } from "@/lib/settings";
import { site } from "@/lib/constants";

export async function POST(request: Request) { const user = await getCurrentUser(); if (!user || (user.role !== "ADMIN" && user.role !== "STAFF")) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await request.json().catch(() => null) as { type?: "discord" | "email" | "razorpay" } | null; const settings = await getPrivateSettings(); try { if (body?.type === "discord") { const delivered = await sendEmbedNow(createEmbed({ title: "✅ Discord settings test", description: "Joyguru Enterprise notifications are connected.", color: discordColors.success, fields: [{ name: "Triggered by", value: user.email }, { name: "Time", value: new Date().toISOString() }] })); if (!delivered) return NextResponse.json({ error: "Discord rejected the test notification." }, { status: 502 }); return NextResponse.json({ ok: true, message: "Discord test sent." }); } if (body?.type === "email") { if (!settings.email.resendApiKey || !settings.email.senderEmail) return NextResponse.json({ error: "Configure Resend API key and sender email first." }, { status: 400 }); const resend = new Resend(settings.email.resendApiKey); const result = await resend.emails.send({ from: `${settings.email.senderName || site.name} <${settings.email.senderEmail}>`, to: user.email, replyTo: settings.email.replyTo || undefined, subject: "Joyguru Enterprise email settings test", text: "Your Joyguru Enterprise email settings are working." }); if (result.error) return NextResponse.json({ error: result.error.message }, { status: 502 }); return NextResponse.json({ ok: true, message: `Test email sent to ${user.email}.` }); } if (body?.type === "razorpay") { if (!settings.payment.razorpayKeyId || !settings.payment.razorpaySecret) return NextResponse.json({ error: "Configure Razorpay credentials first." }, { status: 400 }); const razorpay = new Razorpay({ key_id: settings.payment.razorpayKeyId, key_secret: settings.payment.razorpaySecret }); await razorpay.orders.all({ count: 1 }); return NextResponse.json({ ok: true, message: "Razorpay credentials accepted." }); } return NextResponse.json({ error: "Unknown test type." }, { status: 400 }); } catch { return NextResponse.json({ error: "The provider test failed. Check credentials and try again." }, { status: 502 }); } }
