"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
export default function WarehousesPage() { const [warehouses, setWarehouses] = useState<{ id: string; name: string; address: string; manager: string; _count: { stocks: number; batches: number } }[]>([]); const [form, setForm] = useState({ name: "", address: "", manager: "" }); const load = async () => { const response = await fetch("/api/admin/warehouses", { cache: "no-store" }); if (response.ok) setWarehouses((await response.json() as { warehouses: typeof warehouses }).warehouses); };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []); const save = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch("/api/admin/warehouses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { setForm({ name: "", address: "", manager: "" }); await load(); } }; return <main className="container-shell py-12 lg:py-20"><a href="/admin/inventory" className="text-xs font-semibold text-muted">← Inventory</a><h1 className="section-title mt-8">Warehouses.</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px]"><section className="grid gap-4 sm:grid-cols-2">{warehouses.map((warehouse) => <div key={warehouse.id} className="surface p-6"><p className="text-lg font-semibold">{warehouse.name}</p><p className="mt-2 text-sm text-muted">{warehouse.address}</p><p className="mt-5 text-xs uppercase tracking-[.12em] text-clay-500">Manager · {warehouse.manager}</p><p className="mt-3 text-xs text-muted">{warehouse._count.stocks} stock records · {warehouse._count.batches} batches</p></div>)}{!warehouses.length && <div className="surface p-10 text-sm text-muted">No warehouses yet.</div>}</section><form onSubmit={save} className="surface space-y-4 p-6"><p className="eyebrow">New warehouse</p><div><Label>Name</Label><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></div><div><Label>Address</Label><Input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} required /></div><div><Label>Manager</Label><Input value={form.manager} onChange={(event) => setForm({ ...form, manager: event.target.value })} required /></div><Button type="submit">Add warehouse</Button></form></div></main>; }
